title: 上司・同僚との効果的な連携術
default_lang: ja
display_complete_alert: on
complete_flg_scene:
scene_menu: on
multi_lang: off
popup_explanation_text: このユニットは終了です。お疲れ様でした
popup_next_unit_text: 次のユニットへ
popup_close_text: 終了する
label_text: 言語を選択してください
lang:
  - ja
frames:
  - main:
      name: workskill02-collaboration
      type: slide
