title: 初期対応の重要性（謝罪と傾聴）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-claim-initial/slide/1.jpg"
  - "@scenes/slide/call-claim-initial/slide/2.jpg"
  - "@scenes/slide/call-claim-initial/slide/3.jpg"
  - "@scenes/slide/call-claim-initial/slide/4.jpg"
  - "@scenes/slide/call-claim-initial/slide/5.jpg"
  - "@scenes/slide/call-claim-initial/slide/6.jpg"
  - "@scenes/slide/call-claim-initial/slide/7.jpg"
  - "@scenes/slide/call-claim-initial/slide/8.jpg"
  - "@scenes/slide/call-claim-initial/slide/9.jpg"
  - "@scenes/slide/call-claim-initial/slide/10.jpg"
  - "@scenes/slide/call-claim-initial/slide/11.jpg"
  - "@scenes/slide/call-claim-initial/slide/12.jpg"
  - "@scenes/slide/call-claim-initial/slide/13.jpg"
  - "@scenes/slide/call-claim-initial/slide/14.jpg"
  - "@scenes/slide/call-claim-initial/slide/15.jpg"
  - "@scenes/slide/call-claim-initial/slide/16.jpg"
  - "@scenes/slide/call-claim-initial/slide/17.jpg"
  - "@scenes/slide/call-claim-initial/slide/18.jpg"
  - "@scenes/slide/call-claim-initial/slide/19.jpg"
  - "@scenes/slide/call-claim-initial/slide/20.jpg"
  - "@scenes/slide/call-claim-initial/slide/21.jpg"
  - "@scenes/slide/call-claim-initial/slide/22.jpg"
  - "@scenes/slide/call-claim-initial/slide/23.jpg"
  - "@scenes/slide/call-claim-initial/slide/24.jpg"
  - "@scenes/slide/call-claim-initial/slide/25.jpg"
  - "@scenes/slide/call-claim-initial/slide/26.jpg"
  - "@scenes/slide/call-claim-initial/slide/27.jpg"
  - "@scenes/slide/call-claim-initial/slide/28.jpg"
  - "@scenes/slide/call-claim-initial/slide/29.jpg"
  - "@scenes/slide/call-claim-initial/slide/30.jpg"
  - "@scenes/slide/call-claim-initial/slide/31.jpg"
  - "@scenes/slide/call-claim-initial/slide/32.jpg"
  - "@scenes/slide/call-claim-initial/slide/33.jpg"
  - "@scenes/slide/call-claim-initial/slide/34.jpg"
  - "@scenes/slide/call-claim-initial/slide/35.jpg"
  - "@scenes/slide/call-claim-initial/slide/36.jpg"
  - "@scenes/slide/call-claim-initial/slide/37.jpg"
  - "@scenes/slide/call-claim-initial/slide/38.jpg"
  - "@scenes/slide/call-claim-initial/slide/39.jpg"
  - "@scenes/slide/call-claim-initial/slide/40.jpg"
  - "@scenes/slide/call-claim-initial/slide/41.jpg"
  - "@scenes/slide/call-claim-initial/slide/42.jpg"
  - "@scenes/slide/call-claim-initial/slide/43.jpg"
  - "@scenes/slide/call-claim-initial/slide/44.jpg"
  - "@scenes/slide/call-claim-initial/slide/45.jpg"
  - "@scenes/slide/call-claim-initial/slide/46.jpg"
  - "@scenes/slide/call-claim-initial/slide/47.jpg"
  - "@scenes/slide/call-claim-initial/slide/48.jpg"
  - "@scenes/slide/call-claim-initial/slide/49.jpg"
  - "@scenes/slide/call-claim-initial/slide/50.jpg"
  - "@scenes/slide/call-claim-initial/slide/51.jpg"
  - "@scenes/slide/call-claim-initial/slide/52.jpg"
  - "@scenes/slide/call-claim-initial/slide/53.jpg"
  - "@scenes/slide/call-claim-initial/slide/54.jpg"
  - "@scenes/slide/call-claim-initial/slide/55.jpg"
