title: 初期対応の重要性（謝罪と傾聴）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-claim-initial/slide/1.png"
  - "@scenes/slide/call-claim-initial/slide/2.png"
  - "@scenes/slide/call-claim-initial/slide/3.png"
  - "@scenes/slide/call-claim-initial/slide/4.png"
  - "@scenes/slide/call-claim-initial/slide/5.png"
  - "@scenes/slide/call-claim-initial/slide/6.png"
  - "@scenes/slide/call-claim-initial/slide/7.png"
  - "@scenes/slide/call-claim-initial/slide/8.png"
  - "@scenes/slide/call-claim-initial/slide/9.png"
  - "@scenes/slide/call-claim-initial/slide/10.png"
  - "@scenes/slide/call-claim-initial/slide/11.png"
  - "@scenes/slide/call-claim-initial/slide/12.png"
  - "@scenes/slide/call-claim-initial/slide/13.png"
  - "@scenes/slide/call-claim-initial/slide/14.png"
  - "@scenes/slide/call-claim-initial/slide/15.png"
  - "@scenes/slide/call-claim-initial/slide/16.png"
  - "@scenes/slide/call-claim-initial/slide/17.png"
  - "@scenes/slide/call-claim-initial/slide/18.png"
  - "@scenes/slide/call-claim-initial/slide/19.png"
  - "@scenes/slide/call-claim-initial/slide/20.png"
  - "@scenes/slide/call-claim-initial/slide/21.png"
  - "@scenes/slide/call-claim-initial/slide/22.png"
  - "@scenes/slide/call-claim-initial/slide/23.png"
  - "@scenes/slide/call-claim-initial/slide/24.png"
  - "@scenes/slide/call-claim-initial/slide/25.png"
  - "@scenes/slide/call-claim-initial/slide/26.png"
  - "@scenes/slide/call-claim-initial/slide/27.png"
  - "@scenes/slide/call-claim-initial/slide/28.png"
  - "@scenes/slide/call-claim-initial/slide/29.png"
  - "@scenes/slide/call-claim-initial/slide/30.png"
  - "@scenes/slide/call-claim-initial/slide/31.png"
  - "@scenes/slide/call-claim-initial/slide/32.png"
  - "@scenes/slide/call-claim-initial/slide/33.png"
  - "@scenes/slide/call-claim-initial/slide/34.png"
  - "@scenes/slide/call-claim-initial/slide/35.png"
  - "@scenes/slide/call-claim-initial/slide/36.png"
  - "@scenes/slide/call-claim-initial/slide/37.png"
  - "@scenes/slide/call-claim-initial/slide/38.png"
  - "@scenes/slide/call-claim-initial/slide/39.png"
  - "@scenes/slide/call-claim-initial/slide/40.png"
  - "@scenes/slide/call-claim-initial/slide/41.png"
  - "@scenes/slide/call-claim-initial/slide/42.png"
  - "@scenes/slide/call-claim-initial/slide/43.png"
  - "@scenes/slide/call-claim-initial/slide/44.png"
  - "@scenes/slide/call-claim-initial/slide/45.png"
  - "@scenes/slide/call-claim-initial/slide/46.png"
  - "@scenes/slide/call-claim-initial/slide/47.png"
  - "@scenes/slide/call-claim-initial/slide/48.png"
  - "@scenes/slide/call-claim-initial/slide/49.png"
  - "@scenes/slide/call-claim-initial/slide/50.png"
  - "@scenes/slide/call-claim-initial/slide/51.png"
  - "@scenes/slide/call-claim-initial/slide/52.png"
  - "@scenes/slide/call-claim-initial/slide/53.png"
  - "@scenes/slide/call-claim-initial/slide/54.png"
  - "@scenes/slide/call-claim-initial/slide/55.png"
