title: 初期対応の重要性（謝罪と傾聴）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-claim-initial/slide/1.jpg"
  - "@scenes/slide/call-claim-initial/slide/2.jpg"
  - "@scenes/slide/call-claim-initial/slide/3.jpg"
  - "@scenes/slide/call-claim-initial/slide/4.jpg"
  - "@scenes/slide/call-claim-initial/slide/5.jpg"
  - "@scenes/slide/call-claim-initial/slide/6.jpg"
  - "@scenes/slide/call-claim-initial/slide/7.jpg"
  - "@scenes/slide/call-claim-initial/slide/8.jpg"
  - "@scenes/slide/call-claim-initial/slide/9.jpg"
  - "@scenes/slide/call-claim-initial/slide/10.jpg"
  - "@scenes/slide/call-claim-initial/slide/11.jpg"
  - "@scenes/slide/call-claim-initial/slide/12.jpg"
  - "@scenes/slide/call-claim-initial/slide/13.jpg"
  - "@scenes/slide/call-claim-initial/slide/14.jpg"
  - "@scenes/slide/call-claim-initial/slide/15.jpg"
  - "@scenes/slide/call-claim-initial/slide/16.jpg"
  - "@scenes/slide/call-claim-initial/slide/17.jpg"
  - "@scenes/slide/call-claim-initial/slide/18.jpg"
  - "@scenes/slide/call-claim-initial/slide/19.jpg"
  - "@scenes/slide/call-claim-initial/slide/20.jpg"
  - "@scenes/slide/call-claim-initial/slide/21.jpg"
  - "@scenes/slide/call-claim-initial/slide/22.jpg"
  - "@scenes/slide/call-claim-initial/slide/23.jpg"
  - "@scenes/slide/call-claim-initial/slide/24.jpg"
  - "@scenes/slide/call-claim-initial/slide/25.jpg"
  - "@scenes/slide/call-claim-initial/slide/26.jpg"
  - "@scenes/slide/call-claim-initial/slide/27.jpg"
  - "@scenes/slide/call-claim-initial/slide/28.jpg"
