title: 職場のルール・文化を読み解く力
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-workplace-culture/slide/1.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/2.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/3.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/4.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/5.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/6.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/7.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/8.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/9.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/10.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/11.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/12.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/13.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/14.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/15.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/16.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/17.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/18.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/19.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/20.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/21.png"
  - "@scenes/slide/workskill01-workplace-culture/slide/22.png"
