title: 上司・同僚との効果的な連携術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-collaboration/slide/1.png"
  - "@scenes/slide/workskill02-collaboration/slide/2.png"
  - "@scenes/slide/workskill02-collaboration/slide/3.png"
  - "@scenes/slide/workskill02-collaboration/slide/4.png"
  - "@scenes/slide/workskill02-collaboration/slide/5.png"
  - "@scenes/slide/workskill02-collaboration/slide/6.png"
  - "@scenes/slide/workskill02-collaboration/slide/7.png"
  - "@scenes/slide/workskill02-collaboration/slide/8.png"
  - "@scenes/slide/workskill02-collaboration/slide/9.png"
  - "@scenes/slide/workskill02-collaboration/slide/10.png"
  - "@scenes/slide/workskill02-collaboration/slide/11.png"
  - "@scenes/slide/workskill02-collaboration/slide/12.png"
  - "@scenes/slide/workskill02-collaboration/slide/13.png"
  - "@scenes/slide/workskill02-collaboration/slide/14.png"
  - "@scenes/slide/workskill02-collaboration/slide/15.png"
  - "@scenes/slide/workskill02-collaboration/slide/16.png"
  - "@scenes/slide/workskill02-collaboration/slide/17.png"
  - "@scenes/slide/workskill02-collaboration/slide/18.png"
  - "@scenes/slide/workskill02-collaboration/slide/19.png"
  - "@scenes/slide/workskill02-collaboration/slide/20.png"
  - "@scenes/slide/workskill02-collaboration/slide/21.png"
  - "@scenes/slide/workskill02-collaboration/slide/22.png"
  - "@scenes/slide/workskill02-collaboration/slide/23.png"
  - "@scenes/slide/workskill02-collaboration/slide/24.png"
  - "@scenes/slide/workskill02-collaboration/slide/25.png"
  - "@scenes/slide/workskill02-collaboration/slide/26.png"
  - "@scenes/slide/workskill02-collaboration/slide/27.png"
  - "@scenes/slide/workskill02-collaboration/slide/28.png"
  - "@scenes/slide/workskill02-collaboration/slide/29.png"
  - "@scenes/slide/workskill02-collaboration/slide/30.png"
  - "@scenes/slide/workskill02-collaboration/slide/31.png"
  - "@scenes/slide/workskill02-collaboration/slide/32.png"
  - "@scenes/slide/workskill02-collaboration/slide/33.png"
  - "@scenes/slide/workskill02-collaboration/slide/34.png"
  - "@scenes/slide/workskill02-collaboration/slide/35.png"
  - "@scenes/slide/workskill02-collaboration/slide/36.png"
  - "@scenes/slide/workskill02-collaboration/slide/37.png"
  - "@scenes/slide/workskill02-collaboration/slide/38.png"
  - "@scenes/slide/workskill02-collaboration/slide/39.png"
  - "@scenes/slide/workskill02-collaboration/slide/40.png"
  - "@scenes/slide/workskill02-collaboration/slide/41.png"
  - "@scenes/slide/workskill02-collaboration/slide/42.png"
  - "@scenes/slide/workskill02-collaboration/slide/43.png"
  - "@scenes/slide/workskill02-collaboration/slide/44.png"
