title: ミスの防ぎ方とリカバリーの技術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-mistakes/slide/1.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/2.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/3.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/4.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/5.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/6.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/7.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/8.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/9.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/10.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/11.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/12.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/13.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/14.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/15.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/16.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/17.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/18.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/19.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/20.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/21.jpg"
  - "@scenes/slide/workskill01-mistakes/slide/22.jpg"
