title: ミスの防ぎ方とリカバリーの技術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-mistakes/slide/1.png"
  - "@scenes/slide/workskill01-mistakes/slide/2.png"
  - "@scenes/slide/workskill01-mistakes/slide/3.png"
  - "@scenes/slide/workskill01-mistakes/slide/4.png"
  - "@scenes/slide/workskill01-mistakes/slide/5.png"
  - "@scenes/slide/workskill01-mistakes/slide/6.png"
  - "@scenes/slide/workskill01-mistakes/slide/7.png"
  - "@scenes/slide/workskill01-mistakes/slide/8.png"
  - "@scenes/slide/workskill01-mistakes/slide/9.png"
  - "@scenes/slide/workskill01-mistakes/slide/10.png"
  - "@scenes/slide/workskill01-mistakes/slide/11.png"
  - "@scenes/slide/workskill01-mistakes/slide/12.png"
  - "@scenes/slide/workskill01-mistakes/slide/13.png"
  - "@scenes/slide/workskill01-mistakes/slide/14.png"
  - "@scenes/slide/workskill01-mistakes/slide/15.png"
  - "@scenes/slide/workskill01-mistakes/slide/16.png"
  - "@scenes/slide/workskill01-mistakes/slide/17.png"
  - "@scenes/slide/workskill01-mistakes/slide/18.png"
  - "@scenes/slide/workskill01-mistakes/slide/19.png"
  - "@scenes/slide/workskill01-mistakes/slide/20.png"
  - "@scenes/slide/workskill01-mistakes/slide/21.png"
  - "@scenes/slide/workskill01-mistakes/slide/22.png"
