title: ミスの防ぎ方とリカバリーの技術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-mistakes/slide/1.png"
  - "@scenes/slide/workskill01-mistakes/slide/2.png"
  - "@scenes/slide/workskill01-mistakes/slide/3.png"
  - "@scenes/slide/workskill01-mistakes/slide/4.png"
  - "@scenes/slide/workskill01-mistakes/slide/5.png"
  - "@scenes/slide/workskill01-mistakes/slide/6.png"
  - "@scenes/slide/workskill01-mistakes/slide/7.png"
  - "@scenes/slide/workskill01-mistakes/slide/8.png"
  - "@scenes/slide/workskill01-mistakes/slide/9.png"
  - "@scenes/slide/workskill01-mistakes/slide/10.png"
  - "@scenes/slide/workskill01-mistakes/slide/11.png"
  - "@scenes/slide/workskill01-mistakes/slide/12.png"
  - "@scenes/slide/workskill01-mistakes/slide/13.png"
  - "@scenes/slide/workskill01-mistakes/slide/14.png"
  - "@scenes/slide/workskill01-mistakes/slide/15.png"
  - "@scenes/slide/workskill01-mistakes/slide/16.png"
  - "@scenes/slide/workskill01-mistakes/slide/17.png"
  - "@scenes/slide/workskill01-mistakes/slide/18.png"
  - "@scenes/slide/workskill01-mistakes/slide/19.png"
  - "@scenes/slide/workskill01-mistakes/slide/20.png"
  - "@scenes/slide/workskill01-mistakes/slide/21.png"
  - "@scenes/slide/workskill01-mistakes/slide/22.png"
  - "@scenes/slide/workskill01-mistakes/slide/23.png"
  - "@scenes/slide/workskill01-mistakes/slide/24.png"
  - "@scenes/slide/workskill01-mistakes/slide/25.png"
  - "@scenes/slide/workskill01-mistakes/slide/26.png"
  - "@scenes/slide/workskill01-mistakes/slide/27.png"
  - "@scenes/slide/workskill01-mistakes/slide/28.png"
  - "@scenes/slide/workskill01-mistakes/slide/29.png"
  - "@scenes/slide/workskill01-mistakes/slide/30.png"
  - "@scenes/slide/workskill01-mistakes/slide/31.png"
  - "@scenes/slide/workskill01-mistakes/slide/32.png"
  - "@scenes/slide/workskill01-mistakes/slide/33.png"
  - "@scenes/slide/workskill01-mistakes/slide/34.png"
  - "@scenes/slide/workskill01-mistakes/slide/35.png"
  - "@scenes/slide/workskill01-mistakes/slide/36.png"
  - "@scenes/slide/workskill01-mistakes/slide/37.png"
  - "@scenes/slide/workskill01-mistakes/slide/38.png"
  - "@scenes/slide/workskill01-mistakes/slide/39.png"
  - "@scenes/slide/workskill01-mistakes/slide/40.png"
  - "@scenes/slide/workskill01-mistakes/slide/41.png"
  - "@scenes/slide/workskill01-mistakes/slide/42.png"
  - "@scenes/slide/workskill01-mistakes/slide/43.png"
  - "@scenes/slide/workskill01-mistakes/slide/44.png"
