title: 個人情報の取得・利用・提供のルール
default_lang: ja
display_complete_alert: on
complete_flg_scene:
scene_menu: on
multi_lang: on
popup_explanation_text: このユニットは終了です。お疲れ様でした
popup_next_unit_text: 次のユニットへ
popup_close_text: メニューに戻る
label_text: 言語を選択してください
lang:
  - ja
  - en
frames:
  - main:
      name: privacy-rules
      type: slide
