title: 主体的に働くマインドセット
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-mindset/slide/1.png"
  - "@scenes/slide/workskill03-mindset/slide/2.png"
  - "@scenes/slide/workskill03-mindset/slide/3.png"
  - "@scenes/slide/workskill03-mindset/slide/4.png"
  - "@scenes/slide/workskill03-mindset/slide/5.png"
  - "@scenes/slide/workskill03-mindset/slide/6.png"
  - "@scenes/slide/workskill03-mindset/slide/7.png"
  - "@scenes/slide/workskill03-mindset/slide/8.png"
  - "@scenes/slide/workskill03-mindset/slide/9.png"
  - "@scenes/slide/workskill03-mindset/slide/10.png"
  - "@scenes/slide/workskill03-mindset/slide/11.png"
  - "@scenes/slide/workskill03-mindset/slide/12.png"
  - "@scenes/slide/workskill03-mindset/slide/13.png"
  - "@scenes/slide/workskill03-mindset/slide/14.png"
  - "@scenes/slide/workskill03-mindset/slide/15.png"
  - "@scenes/slide/workskill03-mindset/slide/16.png"
  - "@scenes/slide/workskill03-mindset/slide/17.png"
  - "@scenes/slide/workskill03-mindset/slide/18.png"
  - "@scenes/slide/workskill03-mindset/slide/19.png"
  - "@scenes/slide/workskill03-mindset/slide/20.png"
  - "@scenes/slide/workskill03-mindset/slide/21.png"
  - "@scenes/slide/workskill03-mindset/slide/22.png"
