title: 仕事への向き合い方とプロ意識
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-professional/slide/1.jpg"
  - "@scenes/slide/workskill02-professional/slide/2.jpg"
  - "@scenes/slide/workskill02-professional/slide/3.jpg"
  - "@scenes/slide/workskill02-professional/slide/4.jpg"
  - "@scenes/slide/workskill02-professional/slide/5.jpg"
  - "@scenes/slide/workskill02-professional/slide/6.jpg"
  - "@scenes/slide/workskill02-professional/slide/7.jpg"
  - "@scenes/slide/workskill02-professional/slide/8.jpg"
  - "@scenes/slide/workskill02-professional/slide/9.jpg"
  - "@scenes/slide/workskill02-professional/slide/10.jpg"
  - "@scenes/slide/workskill02-professional/slide/11.jpg"
  - "@scenes/slide/workskill02-professional/slide/12.jpg"
  - "@scenes/slide/workskill02-professional/slide/13.jpg"
  - "@scenes/slide/workskill02-professional/slide/14.jpg"
  - "@scenes/slide/workskill02-professional/slide/15.jpg"
  - "@scenes/slide/workskill02-professional/slide/16.jpg"
  - "@scenes/slide/workskill02-professional/slide/17.jpg"
  - "@scenes/slide/workskill02-professional/slide/18.jpg"
  - "@scenes/slide/workskill02-professional/slide/19.jpg"
  - "@scenes/slide/workskill02-professional/slide/20.jpg"
  - "@scenes/slide/workskill02-professional/slide/21.jpg"
  - "@scenes/slide/workskill02-professional/slide/22.jpg"
