title: 仕事への向き合い方とプロ意識
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-professional/slide/1.png"
  - "@scenes/slide/workskill02-professional/slide/2.png"
  - "@scenes/slide/workskill02-professional/slide/3.png"
  - "@scenes/slide/workskill02-professional/slide/4.png"
  - "@scenes/slide/workskill02-professional/slide/5.png"
  - "@scenes/slide/workskill02-professional/slide/6.png"
  - "@scenes/slide/workskill02-professional/slide/7.png"
  - "@scenes/slide/workskill02-professional/slide/8.png"
  - "@scenes/slide/workskill02-professional/slide/9.png"
  - "@scenes/slide/workskill02-professional/slide/10.png"
  - "@scenes/slide/workskill02-professional/slide/11.png"
  - "@scenes/slide/workskill02-professional/slide/12.png"
  - "@scenes/slide/workskill02-professional/slide/13.png"
  - "@scenes/slide/workskill02-professional/slide/14.png"
  - "@scenes/slide/workskill02-professional/slide/15.png"
  - "@scenes/slide/workskill02-professional/slide/16.png"
  - "@scenes/slide/workskill02-professional/slide/17.png"
  - "@scenes/slide/workskill02-professional/slide/18.png"
  - "@scenes/slide/workskill02-professional/slide/19.png"
  - "@scenes/slide/workskill02-professional/slide/20.png"
  - "@scenes/slide/workskill02-professional/slide/21.png"
  - "@scenes/slide/workskill02-professional/slide/22.png"
  - "@scenes/slide/workskill02-professional/slide/23.png"
  - "@scenes/slide/workskill02-professional/slide/24.png"
  - "@scenes/slide/workskill02-professional/slide/25.png"
  - "@scenes/slide/workskill02-professional/slide/26.png"
  - "@scenes/slide/workskill02-professional/slide/27.png"
  - "@scenes/slide/workskill02-professional/slide/28.png"
  - "@scenes/slide/workskill02-professional/slide/29.png"
  - "@scenes/slide/workskill02-professional/slide/30.png"
  - "@scenes/slide/workskill02-professional/slide/31.png"
  - "@scenes/slide/workskill02-professional/slide/32.png"
  - "@scenes/slide/workskill02-professional/slide/33.png"
  - "@scenes/slide/workskill02-professional/slide/34.png"
  - "@scenes/slide/workskill02-professional/slide/35.png"
  - "@scenes/slide/workskill02-professional/slide/36.png"
  - "@scenes/slide/workskill02-professional/slide/37.png"
  - "@scenes/slide/workskill02-professional/slide/38.png"
  - "@scenes/slide/workskill02-professional/slide/39.png"
  - "@scenes/slide/workskill02-professional/slide/40.png"
  - "@scenes/slide/workskill02-professional/slide/41.png"
  - "@scenes/slide/workskill02-professional/slide/42.png"
  - "@scenes/slide/workskill02-professional/slide/43.png"
  - "@scenes/slide/workskill02-professional/slide/44.png"
