title: モチベーションの自己管理術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-motivation/slide/1.png"
  - "@scenes/slide/workskill02-motivation/slide/2.png"
  - "@scenes/slide/workskill02-motivation/slide/3.png"
  - "@scenes/slide/workskill02-motivation/slide/4.png"
  - "@scenes/slide/workskill02-motivation/slide/5.png"
  - "@scenes/slide/workskill02-motivation/slide/6.png"
  - "@scenes/slide/workskill02-motivation/slide/7.png"
  - "@scenes/slide/workskill02-motivation/slide/8.png"
  - "@scenes/slide/workskill02-motivation/slide/9.png"
  - "@scenes/slide/workskill02-motivation/slide/10.png"
  - "@scenes/slide/workskill02-motivation/slide/11.png"
  - "@scenes/slide/workskill02-motivation/slide/12.png"
  - "@scenes/slide/workskill02-motivation/slide/13.png"
  - "@scenes/slide/workskill02-motivation/slide/14.png"
  - "@scenes/slide/workskill02-motivation/slide/15.png"
  - "@scenes/slide/workskill02-motivation/slide/16.png"
  - "@scenes/slide/workskill02-motivation/slide/17.png"
  - "@scenes/slide/workskill02-motivation/slide/18.png"
  - "@scenes/slide/workskill02-motivation/slide/19.png"
  - "@scenes/slide/workskill02-motivation/slide/20.png"
  - "@scenes/slide/workskill02-motivation/slide/21.png"
  - "@scenes/slide/workskill02-motivation/slide/22.png"
