title: モチベーションの自己管理術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-motivation/slide/1.jpg"
  - "@scenes/slide/workskill02-motivation/slide/2.jpg"
  - "@scenes/slide/workskill02-motivation/slide/3.jpg"
  - "@scenes/slide/workskill02-motivation/slide/4.jpg"
  - "@scenes/slide/workskill02-motivation/slide/5.jpg"
  - "@scenes/slide/workskill02-motivation/slide/6.jpg"
  - "@scenes/slide/workskill02-motivation/slide/7.jpg"
  - "@scenes/slide/workskill02-motivation/slide/8.jpg"
  - "@scenes/slide/workskill02-motivation/slide/9.jpg"
  - "@scenes/slide/workskill02-motivation/slide/10.jpg"
  - "@scenes/slide/workskill02-motivation/slide/11.jpg"
  - "@scenes/slide/workskill02-motivation/slide/12.jpg"
  - "@scenes/slide/workskill02-motivation/slide/13.jpg"
  - "@scenes/slide/workskill02-motivation/slide/14.jpg"
  - "@scenes/slide/workskill02-motivation/slide/15.jpg"
  - "@scenes/slide/workskill02-motivation/slide/16.jpg"
  - "@scenes/slide/workskill02-motivation/slide/17.jpg"
  - "@scenes/slide/workskill02-motivation/slide/18.jpg"
  - "@scenes/slide/workskill02-motivation/slide/19.jpg"
  - "@scenes/slide/workskill02-motivation/slide/20.jpg"
  - "@scenes/slide/workskill02-motivation/slide/21.jpg"
  - "@scenes/slide/workskill02-motivation/slide/22.jpg"
