title: 信頼関係の構築と自己成長の振り返り
default_lang: ja
display_complete_alert: off
complete_flg_scene:
scene_menu: on
multi_lang: off
popup_explanation_text: このユニットは終了です。お疲れ様でした
popup_next_unit_text: 次のユニットへ
popup_close_text: 終了する
label_text: 言語を選択してください
lang:
  - ja
frames:
  - main:
      name: workskill01-trust-growth
      type: slide
