title: キャリア自律と市場価値の高め方
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-career/slide/1.jpg"
  - "@scenes/slide/workskill03-career/slide/2.jpg"
  - "@scenes/slide/workskill03-career/slide/3.jpg"
  - "@scenes/slide/workskill03-career/slide/4.jpg"
  - "@scenes/slide/workskill03-career/slide/5.jpg"
  - "@scenes/slide/workskill03-career/slide/6.jpg"
  - "@scenes/slide/workskill03-career/slide/7.jpg"
  - "@scenes/slide/workskill03-career/slide/8.jpg"
  - "@scenes/slide/workskill03-career/slide/9.jpg"
  - "@scenes/slide/workskill03-career/slide/10.jpg"
  - "@scenes/slide/workskill03-career/slide/11.jpg"
  - "@scenes/slide/workskill03-career/slide/12.jpg"
  - "@scenes/slide/workskill03-career/slide/13.jpg"
  - "@scenes/slide/workskill03-career/slide/14.jpg"
  - "@scenes/slide/workskill03-career/slide/15.jpg"
  - "@scenes/slide/workskill03-career/slide/16.jpg"
  - "@scenes/slide/workskill03-career/slide/17.jpg"
  - "@scenes/slide/workskill03-career/slide/18.jpg"
  - "@scenes/slide/workskill03-career/slide/19.jpg"
  - "@scenes/slide/workskill03-career/slide/20.jpg"
  - "@scenes/slide/workskill03-career/slide/21.jpg"
  - "@scenes/slide/workskill03-career/slide/22.jpg"
