title: 日常業務とインシデント対応
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/security-daily/slide/1.png"
  - "@scenes/slide/security-daily/slide/2.png"
  - "@scenes/slide/security-daily/slide/3.png"
  - "@scenes/slide/security-daily/slide/4.png"
  - "@scenes/slide/security-daily/slide/5.png"
  - "@scenes/slide/security-daily/slide/6.png"
  - "@scenes/slide/security-daily/slide/7.png"
  - "@scenes/slide/security-daily/slide/8.png"
  - "@scenes/slide/security-daily/slide/9.png"
  - "@scenes/slide/security-daily/slide/10.png"
  - "@scenes/slide/security-daily/slide/11.png"
  - "@scenes/slide/security-daily/slide/12.png"
  - "@scenes/slide/security-daily/slide/13.png"
  - "@scenes/slide/security-daily/slide/14.png"
  - "@scenes/slide/security-daily/slide/15.png"
  - "@scenes/slide/security-daily/slide/16.png"
  - "@scenes/slide/security-daily/slide/17.png"
  - "@scenes/slide/security-daily/slide/18.png"
  - "@scenes/slide/security-daily/slide/19.png"
  - "@scenes/slide/security-daily/slide/20.png"
  - "@scenes/slide/security-daily/slide/21.png"
  - "@scenes/slide/security-daily/slide/22.png"
  - "@scenes/slide/security-daily/slide/23.png"
