title: 指導とパワハラの境界線（グレーゾーン）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-power-gray/slide/1.png"
  - "@scenes/slide/harass-power-gray/slide/2.png"
  - "@scenes/slide/harass-power-gray/slide/3.png"
  - "@scenes/slide/harass-power-gray/slide/4.png"
  - "@scenes/slide/harass-power-gray/slide/5.png"
  - "@scenes/slide/harass-power-gray/slide/6.png"
  - "@scenes/slide/harass-power-gray/slide/7.png"
  - "@scenes/slide/harass-power-gray/slide/8.png"
  - "@scenes/slide/harass-power-gray/slide/9.png"
  - "@scenes/slide/harass-power-gray/slide/10.png"
  - "@scenes/slide/harass-power-gray/slide/11.png"
  - "@scenes/slide/harass-power-gray/slide/12.png"
  - "@scenes/slide/harass-power-gray/slide/13.png"
  - "@scenes/slide/harass-power-gray/slide/14.png"
  - "@scenes/slide/harass-power-gray/slide/15.png"
  - "@scenes/slide/harass-power-gray/slide/16.png"
  - "@scenes/slide/harass-power-gray/slide/17.png"
  - "@scenes/slide/harass-power-gray/slide/18.png"
  - "@scenes/slide/harass-power-gray/slide/19.png"
  - "@scenes/slide/harass-power-gray/slide/20.png"
  - "@scenes/slide/harass-power-gray/slide/21.png"
  - "@scenes/slide/harass-power-gray/slide/22.png"
  - "@scenes/slide/harass-power-gray/slide/23.png"
  - "@scenes/slide/harass-power-gray/slide/24.png"
  - "@scenes/slide/harass-power-gray/slide/25.png"
  - "@scenes/slide/harass-power-gray/slide/26.png"
  - "@scenes/slide/harass-power-gray/slide/27.png"
  - "@scenes/slide/harass-power-gray/slide/28.png"
  - "@scenes/slide/harass-power-gray/slide/29.png"
  - "@scenes/slide/harass-power-gray/slide/30.png"
  - "@scenes/slide/harass-power-gray/slide/31.png"
  - "@scenes/slide/harass-power-gray/slide/32.png"
  - "@scenes/slide/harass-power-gray/slide/33.png"
  - "@scenes/slide/harass-power-gray/slide/34.png"
  - "@scenes/slide/harass-power-gray/slide/35.png"
  - "@scenes/slide/harass-power-gray/slide/36.png"
  - "@scenes/slide/harass-power-gray/slide/37.png"
  - "@scenes/slide/harass-power-gray/slide/38.png"
  - "@scenes/slide/harass-power-gray/slide/39.png"
  - "@scenes/slide/harass-power-gray/slide/40.png"
  - "@scenes/slide/harass-power-gray/slide/41.png"
  - "@scenes/slide/harass-power-gray/slide/42.png"
  - "@scenes/slide/harass-power-gray/slide/43.png"
  - "@scenes/slide/harass-power-gray/slide/44.png"
  - "@scenes/slide/harass-power-gray/slide/45.png"
  - "@scenes/slide/harass-power-gray/slide/46.png"
  - "@scenes/slide/harass-power-gray/slide/47.png"
  - "@scenes/slide/harass-power-gray/slide/48.png"
  - "@scenes/slide/harass-power-gray/slide/49.png"
  - "@scenes/slide/harass-power-gray/slide/50.png"
  - "@scenes/slide/harass-power-gray/slide/51.png"
