title: 指導とパワハラの境界線（グレーゾーン）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-power-gray/slide/1.jpg"
  - "@scenes/slide/harass-power-gray/slide/2.jpg"
  - "@scenes/slide/harass-power-gray/slide/3.jpg"
  - "@scenes/slide/harass-power-gray/slide/4.jpg"
  - "@scenes/slide/harass-power-gray/slide/5.jpg"
  - "@scenes/slide/harass-power-gray/slide/6.jpg"
  - "@scenes/slide/harass-power-gray/slide/7.jpg"
  - "@scenes/slide/harass-power-gray/slide/8.jpg"
  - "@scenes/slide/harass-power-gray/slide/9.jpg"
  - "@scenes/slide/harass-power-gray/slide/10.jpg"
  - "@scenes/slide/harass-power-gray/slide/11.jpg"
  - "@scenes/slide/harass-power-gray/slide/12.jpg"
  - "@scenes/slide/harass-power-gray/slide/13.jpg"
  - "@scenes/slide/harass-power-gray/slide/14.jpg"
  - "@scenes/slide/harass-power-gray/slide/15.jpg"
  - "@scenes/slide/harass-power-gray/slide/16.jpg"
  - "@scenes/slide/harass-power-gray/slide/17.jpg"
  - "@scenes/slide/harass-power-gray/slide/18.jpg"
  - "@scenes/slide/harass-power-gray/slide/19.jpg"
  - "@scenes/slide/harass-power-gray/slide/20.jpg"
  - "@scenes/slide/harass-power-gray/slide/21.jpg"
  - "@scenes/slide/harass-power-gray/slide/22.jpg"
  - "@scenes/slide/harass-power-gray/slide/23.jpg"
  - "@scenes/slide/harass-power-gray/slide/24.jpg"
  - "@scenes/slide/harass-power-gray/slide/25.jpg"
