title: パワハラの定義と6類型
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-power-def/slide/1.png"
  - "@scenes/slide/harass-power-def/slide/2.png"
  - "@scenes/slide/harass-power-def/slide/3.png"
  - "@scenes/slide/harass-power-def/slide/4.png"
  - "@scenes/slide/harass-power-def/slide/5.png"
  - "@scenes/slide/harass-power-def/slide/6.png"
  - "@scenes/slide/harass-power-def/slide/7.png"
  - "@scenes/slide/harass-power-def/slide/8.png"
  - "@scenes/slide/harass-power-def/slide/9.png"
  - "@scenes/slide/harass-power-def/slide/10.png"
  - "@scenes/slide/harass-power-def/slide/11.png"
  - "@scenes/slide/harass-power-def/slide/12.png"
  - "@scenes/slide/harass-power-def/slide/13.png"
  - "@scenes/slide/harass-power-def/slide/14.png"
  - "@scenes/slide/harass-power-def/slide/15.png"
  - "@scenes/slide/harass-power-def/slide/16.png"
  - "@scenes/slide/harass-power-def/slide/17.png"
  - "@scenes/slide/harass-power-def/slide/18.png"
  - "@scenes/slide/harass-power-def/slide/19.png"
  - "@scenes/slide/harass-power-def/slide/20.png"
  - "@scenes/slide/harass-power-def/slide/21.png"
  - "@scenes/slide/harass-power-def/slide/22.png"
  - "@scenes/slide/harass-power-def/slide/23.png"
  - "@scenes/slide/harass-power-def/slide/24.png"
  - "@scenes/slide/harass-power-def/slide/25.png"
  - "@scenes/slide/harass-power-def/slide/26.png"
  - "@scenes/slide/harass-power-def/slide/27.png"
  - "@scenes/slide/harass-power-def/slide/28.png"
  - "@scenes/slide/harass-power-def/slide/29.png"
  - "@scenes/slide/harass-power-def/slide/30.png"
  - "@scenes/slide/harass-power-def/slide/31.png"
  - "@scenes/slide/harass-power-def/slide/32.png"
  - "@scenes/slide/harass-power-def/slide/33.png"
  - "@scenes/slide/harass-power-def/slide/34.png"
  - "@scenes/slide/harass-power-def/slide/35.png"
  - "@scenes/slide/harass-power-def/slide/36.png"
  - "@scenes/slide/harass-power-def/slide/37.png"
  - "@scenes/slide/harass-power-def/slide/38.png"
  - "@scenes/slide/harass-power-def/slide/39.png"
  - "@scenes/slide/harass-power-def/slide/40.png"
  - "@scenes/slide/harass-power-def/slide/41.png"
  - "@scenes/slide/harass-power-def/slide/42.png"
  - "@scenes/slide/harass-power-def/slide/43.png"
  - "@scenes/slide/harass-power-def/slide/44.png"
  - "@scenes/slide/harass-power-def/slide/45.png"
  - "@scenes/slide/harass-power-def/slide/46.png"
  - "@scenes/slide/harass-power-def/slide/47.png"
  - "@scenes/slide/harass-power-def/slide/48.png"
  - "@scenes/slide/harass-power-def/slide/49.png"
