title: 問題発見力と改善提案の技術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-problem-solving/slide/1.png"
  - "@scenes/slide/workskill02-problem-solving/slide/2.png"
  - "@scenes/slide/workskill02-problem-solving/slide/3.png"
  - "@scenes/slide/workskill02-problem-solving/slide/4.png"
  - "@scenes/slide/workskill02-problem-solving/slide/5.png"
  - "@scenes/slide/workskill02-problem-solving/slide/6.png"
  - "@scenes/slide/workskill02-problem-solving/slide/7.png"
  - "@scenes/slide/workskill02-problem-solving/slide/8.png"
  - "@scenes/slide/workskill02-problem-solving/slide/9.png"
  - "@scenes/slide/workskill02-problem-solving/slide/10.png"
  - "@scenes/slide/workskill02-problem-solving/slide/11.png"
  - "@scenes/slide/workskill02-problem-solving/slide/12.png"
  - "@scenes/slide/workskill02-problem-solving/slide/13.png"
  - "@scenes/slide/workskill02-problem-solving/slide/14.png"
  - "@scenes/slide/workskill02-problem-solving/slide/15.png"
  - "@scenes/slide/workskill02-problem-solving/slide/16.png"
  - "@scenes/slide/workskill02-problem-solving/slide/17.png"
  - "@scenes/slide/workskill02-problem-solving/slide/18.png"
  - "@scenes/slide/workskill02-problem-solving/slide/19.png"
  - "@scenes/slide/workskill02-problem-solving/slide/20.png"
  - "@scenes/slide/workskill02-problem-solving/slide/21.png"
  - "@scenes/slide/workskill02-problem-solving/slide/22.png"
  - "@scenes/slide/workskill02-problem-solving/slide/23.png"
  - "@scenes/slide/workskill02-problem-solving/slide/24.png"
  - "@scenes/slide/workskill02-problem-solving/slide/25.png"
  - "@scenes/slide/workskill02-problem-solving/slide/26.png"
  - "@scenes/slide/workskill02-problem-solving/slide/27.png"
  - "@scenes/slide/workskill02-problem-solving/slide/28.png"
  - "@scenes/slide/workskill02-problem-solving/slide/29.png"
  - "@scenes/slide/workskill02-problem-solving/slide/30.png"
  - "@scenes/slide/workskill02-problem-solving/slide/31.png"
  - "@scenes/slide/workskill02-problem-solving/slide/32.png"
  - "@scenes/slide/workskill02-problem-solving/slide/33.png"
  - "@scenes/slide/workskill02-problem-solving/slide/34.png"
  - "@scenes/slide/workskill02-problem-solving/slide/35.png"
  - "@scenes/slide/workskill02-problem-solving/slide/36.png"
  - "@scenes/slide/workskill02-problem-solving/slide/37.png"
  - "@scenes/slide/workskill02-problem-solving/slide/38.png"
  - "@scenes/slide/workskill02-problem-solving/slide/39.png"
  - "@scenes/slide/workskill02-problem-solving/slide/40.png"
  - "@scenes/slide/workskill02-problem-solving/slide/41.png"
  - "@scenes/slide/workskill02-problem-solving/slide/42.png"
  - "@scenes/slide/workskill02-problem-solving/slide/43.png"
  - "@scenes/slide/workskill02-problem-solving/slide/44.png"
