title: 業務品質と生産性の向上
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-quality-productivity/slide/1.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/2.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/3.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/4.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/5.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/6.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/7.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/8.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/9.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/10.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/11.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/12.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/13.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/14.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/15.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/16.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/17.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/18.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/19.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/20.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/21.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/22.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/23.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/24.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/25.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/26.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/27.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/28.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/29.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/30.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/31.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/32.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/33.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/34.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/35.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/36.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/37.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/38.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/39.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/40.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/41.png"
  - "@scenes/slide/workskill02-quality-productivity/slide/42.png"
