title: 業務品質と生産性の向上
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-quality-productivity/slide/1.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/2.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/3.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/4.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/5.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/6.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/7.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/8.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/9.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/10.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/11.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/12.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/13.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/14.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/15.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/16.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/17.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/18.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/19.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/20.jpg"
  - "@scenes/slide/workskill02-quality-productivity/slide/21.jpg"
