title: 日常業務での実践
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/privacy-practice/slide/1.jpg"
  - "@scenes/slide/privacy-practice/slide/2.jpg"
  - "@scenes/slide/privacy-practice/slide/3.jpg"
  - "@scenes/slide/privacy-practice/slide/4.jpg"
  - "@scenes/slide/privacy-practice/slide/5.jpg"
  - "@scenes/slide/privacy-practice/slide/6.jpg"
  - "@scenes/slide/privacy-practice/slide/7.jpg"
  - "@scenes/slide/privacy-practice/slide/8.jpg"
  - "@scenes/slide/privacy-practice/slide/9.jpg"
  - "@scenes/slide/privacy-practice/slide/10.jpg"
  - "@scenes/slide/privacy-practice/slide/11.jpg"
  - "@scenes/slide/privacy-practice/slide/12.jpg"
  - "@scenes/slide/privacy-practice/slide/13.jpg"
  - "@scenes/slide/privacy-practice/slide/14.jpg"
  - "@scenes/slide/privacy-practice/slide/15.jpg"
  - "@scenes/slide/privacy-practice/slide/16.jpg"
  - "@scenes/slide/privacy-practice/slide/17.jpg"
  - "@scenes/slide/privacy-practice/slide/18.jpg"
  - "@scenes/slide/privacy-practice/slide/19.jpg"
  - "@scenes/slide/privacy-practice/slide/20.jpg"
  - "@scenes/slide/privacy-practice/slide/21.jpg"
  - "@scenes/slide/privacy-practice/slide/22.jpg"
  - "@scenes/slide/privacy-practice/slide/23.jpg"
