title: 当事者意識と「自分ごと化」する力
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-ownership/slide/1.png"
  - "@scenes/slide/workskill02-ownership/slide/2.png"
  - "@scenes/slide/workskill02-ownership/slide/3.png"
  - "@scenes/slide/workskill02-ownership/slide/4.png"
  - "@scenes/slide/workskill02-ownership/slide/5.png"
  - "@scenes/slide/workskill02-ownership/slide/6.png"
  - "@scenes/slide/workskill02-ownership/slide/7.png"
  - "@scenes/slide/workskill02-ownership/slide/8.png"
  - "@scenes/slide/workskill02-ownership/slide/9.png"
  - "@scenes/slide/workskill02-ownership/slide/10.png"
  - "@scenes/slide/workskill02-ownership/slide/11.png"
  - "@scenes/slide/workskill02-ownership/slide/12.png"
  - "@scenes/slide/workskill02-ownership/slide/13.png"
  - "@scenes/slide/workskill02-ownership/slide/14.png"
  - "@scenes/slide/workskill02-ownership/slide/15.png"
  - "@scenes/slide/workskill02-ownership/slide/16.png"
  - "@scenes/slide/workskill02-ownership/slide/17.png"
  - "@scenes/slide/workskill02-ownership/slide/18.png"
  - "@scenes/slide/workskill02-ownership/slide/19.png"
  - "@scenes/slide/workskill02-ownership/slide/20.png"
  - "@scenes/slide/workskill02-ownership/slide/21.png"
  - "@scenes/slide/workskill02-ownership/slide/22.png"
