title: 当事者意識と「自分ごと化」する力
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-ownership/slide/1.jpg"
  - "@scenes/slide/workskill02-ownership/slide/2.jpg"
  - "@scenes/slide/workskill02-ownership/slide/3.jpg"
  - "@scenes/slide/workskill02-ownership/slide/4.jpg"
  - "@scenes/slide/workskill02-ownership/slide/5.jpg"
  - "@scenes/slide/workskill02-ownership/slide/6.jpg"
  - "@scenes/slide/workskill02-ownership/slide/7.jpg"
  - "@scenes/slide/workskill02-ownership/slide/8.jpg"
  - "@scenes/slide/workskill02-ownership/slide/9.jpg"
  - "@scenes/slide/workskill02-ownership/slide/10.jpg"
  - "@scenes/slide/workskill02-ownership/slide/11.jpg"
  - "@scenes/slide/workskill02-ownership/slide/12.jpg"
  - "@scenes/slide/workskill02-ownership/slide/13.jpg"
  - "@scenes/slide/workskill02-ownership/slide/14.jpg"
  - "@scenes/slide/workskill02-ownership/slide/15.jpg"
  - "@scenes/slide/workskill02-ownership/slide/16.jpg"
  - "@scenes/slide/workskill02-ownership/slide/17.jpg"
  - "@scenes/slide/workskill02-ownership/slide/18.jpg"
  - "@scenes/slide/workskill02-ownership/slide/19.jpg"
  - "@scenes/slide/workskill02-ownership/slide/20.jpg"
  - "@scenes/slide/workskill02-ownership/slide/21.jpg"
  - "@scenes/slide/workskill02-ownership/slide/22.jpg"
