title: 当事者意識と「自分ごと化」する力
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-ownership/slide/1.png"
  - "@scenes/slide/workskill02-ownership/slide/2.png"
  - "@scenes/slide/workskill02-ownership/slide/3.png"
  - "@scenes/slide/workskill02-ownership/slide/4.png"
  - "@scenes/slide/workskill02-ownership/slide/5.png"
  - "@scenes/slide/workskill02-ownership/slide/6.png"
  - "@scenes/slide/workskill02-ownership/slide/7.png"
  - "@scenes/slide/workskill02-ownership/slide/8.png"
  - "@scenes/slide/workskill02-ownership/slide/9.png"
  - "@scenes/slide/workskill02-ownership/slide/10.png"
  - "@scenes/slide/workskill02-ownership/slide/11.png"
  - "@scenes/slide/workskill02-ownership/slide/12.png"
  - "@scenes/slide/workskill02-ownership/slide/13.png"
  - "@scenes/slide/workskill02-ownership/slide/14.png"
  - "@scenes/slide/workskill02-ownership/slide/15.png"
  - "@scenes/slide/workskill02-ownership/slide/16.png"
  - "@scenes/slide/workskill02-ownership/slide/17.png"
  - "@scenes/slide/workskill02-ownership/slide/18.png"
  - "@scenes/slide/workskill02-ownership/slide/19.png"
  - "@scenes/slide/workskill02-ownership/slide/20.png"
  - "@scenes/slide/workskill02-ownership/slide/21.png"
  - "@scenes/slide/workskill02-ownership/slide/22.png"
  - "@scenes/slide/workskill02-ownership/slide/23.png"
  - "@scenes/slide/workskill02-ownership/slide/24.png"
  - "@scenes/slide/workskill02-ownership/slide/25.png"
  - "@scenes/slide/workskill02-ownership/slide/26.png"
  - "@scenes/slide/workskill02-ownership/slide/27.png"
  - "@scenes/slide/workskill02-ownership/slide/28.png"
  - "@scenes/slide/workskill02-ownership/slide/29.png"
  - "@scenes/slide/workskill02-ownership/slide/30.png"
  - "@scenes/slide/workskill02-ownership/slide/31.png"
  - "@scenes/slide/workskill02-ownership/slide/32.png"
  - "@scenes/slide/workskill02-ownership/slide/33.png"
  - "@scenes/slide/workskill02-ownership/slide/34.png"
  - "@scenes/slide/workskill02-ownership/slide/35.png"
  - "@scenes/slide/workskill02-ownership/slide/36.png"
  - "@scenes/slide/workskill02-ownership/slide/37.png"
  - "@scenes/slide/workskill02-ownership/slide/38.png"
  - "@scenes/slide/workskill02-ownership/slide/39.png"
  - "@scenes/slide/workskill02-ownership/slide/40.png"
  - "@scenes/slide/workskill02-ownership/slide/41.png"
  - "@scenes/slide/workskill02-ownership/slide/42.png"
  - "@scenes/slide/workskill02-ownership/slide/43.png"
  - "@scenes/slide/workskill02-ownership/slide/44.png"
