title: AIを活用した議事録作成
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/report-minutes-ai/slide/1.png"
  - "@scenes/slide/report-minutes-ai/slide/2.png"
  - "@scenes/slide/report-minutes-ai/slide/3.png"
  - "@scenes/slide/report-minutes-ai/slide/4.png"
  - "@scenes/slide/report-minutes-ai/slide/5.png"
  - "@scenes/slide/report-minutes-ai/slide/6.png"
  - "@scenes/slide/report-minutes-ai/slide/7.png"
  - "@scenes/slide/report-minutes-ai/slide/8.png"
  - "@scenes/slide/report-minutes-ai/slide/9.png"
  - "@scenes/slide/report-minutes-ai/slide/10.png"
  - "@scenes/slide/report-minutes-ai/slide/11.png"
  - "@scenes/slide/report-minutes-ai/slide/12.png"
  - "@scenes/slide/report-minutes-ai/slide/13.png"
  - "@scenes/slide/report-minutes-ai/slide/14.png"
  - "@scenes/slide/report-minutes-ai/slide/15.png"
  - "@scenes/slide/report-minutes-ai/slide/16.png"
  - "@scenes/slide/report-minutes-ai/slide/17.png"
  - "@scenes/slide/report-minutes-ai/slide/18.png"
  - "@scenes/slide/report-minutes-ai/slide/19.png"
  - "@scenes/slide/report-minutes-ai/slide/20.png"
  - "@scenes/slide/report-minutes-ai/slide/21.png"
  - "@scenes/slide/report-minutes-ai/slide/22.png"
  - "@scenes/slide/report-minutes-ai/slide/23.png"
  - "@scenes/slide/report-minutes-ai/slide/24.png"
  - "@scenes/slide/report-minutes-ai/slide/25.png"
  - "@scenes/slide/report-minutes-ai/slide/26.png"
  - "@scenes/slide/report-minutes-ai/slide/27.png"
  - "@scenes/slide/report-minutes-ai/slide/28.png"
  - "@scenes/slide/report-minutes-ai/slide/29.png"
  - "@scenes/slide/report-minutes-ai/slide/30.png"
  - "@scenes/slide/report-minutes-ai/slide/31.png"
  - "@scenes/slide/report-minutes-ai/slide/32.png"
  - "@scenes/slide/report-minutes-ai/slide/33.png"
  - "@scenes/slide/report-minutes-ai/slide/34.png"
  - "@scenes/slide/report-minutes-ai/slide/35.png"
  - "@scenes/slide/report-minutes-ai/slide/36.png"
  - "@scenes/slide/report-minutes-ai/slide/37.png"
  - "@scenes/slide/report-minutes-ai/slide/38.png"
  - "@scenes/slide/report-minutes-ai/slide/39.png"
  - "@scenes/slide/report-minutes-ai/slide/40.png"
  - "@scenes/slide/report-minutes-ai/slide/41.png"
  - "@scenes/slide/report-minutes-ai/slide/42.png"
  - "@scenes/slide/report-minutes-ai/slide/43.png"
  - "@scenes/slide/report-minutes-ai/slide/44.png"
  - "@scenes/slide/report-minutes-ai/slide/45.png"
  - "@scenes/slide/report-minutes-ai/slide/46.png"
  - "@scenes/slide/report-minutes-ai/slide/47.png"
  - "@scenes/slide/report-minutes-ai/slide/48.png"
  - "@scenes/slide/report-minutes-ai/slide/49.png"
  - "@scenes/slide/report-minutes-ai/slide/50.png"
  - "@scenes/slide/report-minutes-ai/slide/51.png"
  - "@scenes/slide/report-minutes-ai/slide/52.png"
  - "@scenes/slide/report-minutes-ai/slide/53.png"
  - "@scenes/slide/report-minutes-ai/slide/54.png"
  - "@scenes/slide/report-minutes-ai/slide/55.png"
  - "@scenes/slide/report-minutes-ai/slide/56.png"
  - "@scenes/slide/report-minutes-ai/slide/57.png"
