title: チームへの貢献と「期待以上」の仕事術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-team-contribution/slide/1.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/2.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/3.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/4.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/5.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/6.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/7.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/8.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/9.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/10.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/11.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/12.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/13.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/14.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/15.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/16.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/17.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/18.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/19.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/20.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/21.jpg"
  - "@scenes/slide/workskill02-team-contribution/slide/22.jpg"
