title: どこでも通用するポータブルスキル
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-portable-skills/slide/1.png"
  - "@scenes/slide/workskill03-portable-skills/slide/2.png"
  - "@scenes/slide/workskill03-portable-skills/slide/3.png"
  - "@scenes/slide/workskill03-portable-skills/slide/4.png"
  - "@scenes/slide/workskill03-portable-skills/slide/5.png"
  - "@scenes/slide/workskill03-portable-skills/slide/6.png"
  - "@scenes/slide/workskill03-portable-skills/slide/7.png"
  - "@scenes/slide/workskill03-portable-skills/slide/8.png"
  - "@scenes/slide/workskill03-portable-skills/slide/9.png"
  - "@scenes/slide/workskill03-portable-skills/slide/10.png"
  - "@scenes/slide/workskill03-portable-skills/slide/11.png"
  - "@scenes/slide/workskill03-portable-skills/slide/12.png"
  - "@scenes/slide/workskill03-portable-skills/slide/13.png"
  - "@scenes/slide/workskill03-portable-skills/slide/14.png"
  - "@scenes/slide/workskill03-portable-skills/slide/15.png"
  - "@scenes/slide/workskill03-portable-skills/slide/16.png"
  - "@scenes/slide/workskill03-portable-skills/slide/17.png"
  - "@scenes/slide/workskill03-portable-skills/slide/18.png"
  - "@scenes/slide/workskill03-portable-skills/slide/19.png"
  - "@scenes/slide/workskill03-portable-skills/slide/20.png"
  - "@scenes/slide/workskill03-portable-skills/slide/21.png"
  - "@scenes/slide/workskill03-portable-skills/slide/22.png"
  - "@scenes/slide/workskill03-portable-skills/slide/23.png"
  - "@scenes/slide/workskill03-portable-skills/slide/24.png"
  - "@scenes/slide/workskill03-portable-skills/slide/25.png"
  - "@scenes/slide/workskill03-portable-skills/slide/26.png"
  - "@scenes/slide/workskill03-portable-skills/slide/27.png"
  - "@scenes/slide/workskill03-portable-skills/slide/28.png"
  - "@scenes/slide/workskill03-portable-skills/slide/29.png"
  - "@scenes/slide/workskill03-portable-skills/slide/30.png"
  - "@scenes/slide/workskill03-portable-skills/slide/31.png"
  - "@scenes/slide/workskill03-portable-skills/slide/32.png"
  - "@scenes/slide/workskill03-portable-skills/slide/33.png"
  - "@scenes/slide/workskill03-portable-skills/slide/34.png"
  - "@scenes/slide/workskill03-portable-skills/slide/35.png"
  - "@scenes/slide/workskill03-portable-skills/slide/36.png"
  - "@scenes/slide/workskill03-portable-skills/slide/37.png"
  - "@scenes/slide/workskill03-portable-skills/slide/38.png"
  - "@scenes/slide/workskill03-portable-skills/slide/39.png"
  - "@scenes/slide/workskill03-portable-skills/slide/40.png"
  - "@scenes/slide/workskill03-portable-skills/slide/41.png"
  - "@scenes/slide/workskill03-portable-skills/slide/42.png"
  - "@scenes/slide/workskill03-portable-skills/slide/43.png"
  - "@scenes/slide/workskill03-portable-skills/slide/44.png"
