title: 新しい環境でのストレスマネジメント
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-stress/slide/1.jpg"
  - "@scenes/slide/workskill01-stress/slide/2.jpg"
  - "@scenes/slide/workskill01-stress/slide/3.jpg"
  - "@scenes/slide/workskill01-stress/slide/4.jpg"
  - "@scenes/slide/workskill01-stress/slide/5.jpg"
  - "@scenes/slide/workskill01-stress/slide/6.jpg"
  - "@scenes/slide/workskill01-stress/slide/7.jpg"
  - "@scenes/slide/workskill01-stress/slide/8.jpg"
  - "@scenes/slide/workskill01-stress/slide/9.jpg"
  - "@scenes/slide/workskill01-stress/slide/10.jpg"
  - "@scenes/slide/workskill01-stress/slide/11.jpg"
  - "@scenes/slide/workskill01-stress/slide/12.jpg"
  - "@scenes/slide/workskill01-stress/slide/13.jpg"
  - "@scenes/slide/workskill01-stress/slide/14.jpg"
  - "@scenes/slide/workskill01-stress/slide/15.jpg"
  - "@scenes/slide/workskill01-stress/slide/16.jpg"
  - "@scenes/slide/workskill01-stress/slide/17.jpg"
  - "@scenes/slide/workskill01-stress/slide/18.jpg"
  - "@scenes/slide/workskill01-stress/slide/19.jpg"
  - "@scenes/slide/workskill01-stress/slide/20.jpg"
  - "@scenes/slide/workskill01-stress/slide/21.jpg"
  - "@scenes/slide/workskill01-stress/slide/22.jpg"
