title: Privacy Protection Basics
btn_next_scene_name: Next
slide_speed: 10
img:
  - "@scenes/slide/privacy-basics/slide/1.jpg"
  - "@scenes/slide/privacy-basics/slide/2.jpg"
  - "@scenes/slide/privacy-basics/slide/3.jpg"
  - "@scenes/slide/privacy-basics/slide/4.jpg"
  - "@scenes/slide/privacy-basics/slide/5.jpg"
  - "@scenes/slide/privacy-basics/slide/6.jpg"
  - "@scenes/slide/privacy-basics/slide/7.jpg"
  - "@scenes/slide/privacy-basics/slide/8.jpg"
  - "@scenes/slide/privacy-basics/slide/9.jpg"
  - "@scenes/slide/privacy-basics/slide/10.jpg"
  - "@scenes/slide/privacy-basics/slide/11.jpg"
  - "@scenes/slide/privacy-basics/slide/12.jpg"
  - "@scenes/slide/privacy-basics/slide/13.jpg"
  - "@scenes/slide/privacy-basics/slide/14.jpg"
  - "@scenes/slide/privacy-basics/slide/15.jpg"
  - "@scenes/slide/privacy-basics/slide/16.jpg"
  - "@scenes/slide/privacy-basics/slide/17.jpg"
  - "@scenes/slide/privacy-basics/slide/18.jpg"
  - "@scenes/slide/privacy-basics/slide/19.jpg"
  - "@scenes/slide/privacy-basics/slide/20.jpg"
  - "@scenes/slide/privacy-basics/slide/21.jpg"
  - "@scenes/slide/privacy-basics/slide/22.jpg"
