title: 議事録の取り方とまとめ方（5W1H）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/report-minutes-5w1h/slide/1.png"
  - "@scenes/slide/report-minutes-5w1h/slide/2.png"
  - "@scenes/slide/report-minutes-5w1h/slide/3.png"
  - "@scenes/slide/report-minutes-5w1h/slide/4.png"
  - "@scenes/slide/report-minutes-5w1h/slide/5.png"
  - "@scenes/slide/report-minutes-5w1h/slide/6.png"
  - "@scenes/slide/report-minutes-5w1h/slide/7.png"
  - "@scenes/slide/report-minutes-5w1h/slide/8.png"
  - "@scenes/slide/report-minutes-5w1h/slide/9.png"
  - "@scenes/slide/report-minutes-5w1h/slide/10.png"
  - "@scenes/slide/report-minutes-5w1h/slide/11.png"
  - "@scenes/slide/report-minutes-5w1h/slide/12.png"
  - "@scenes/slide/report-minutes-5w1h/slide/13.png"
  - "@scenes/slide/report-minutes-5w1h/slide/14.png"
  - "@scenes/slide/report-minutes-5w1h/slide/15.png"
  - "@scenes/slide/report-minutes-5w1h/slide/16.png"
  - "@scenes/slide/report-minutes-5w1h/slide/17.png"
  - "@scenes/slide/report-minutes-5w1h/slide/18.png"
  - "@scenes/slide/report-minutes-5w1h/slide/19.png"
  - "@scenes/slide/report-minutes-5w1h/slide/20.png"
  - "@scenes/slide/report-minutes-5w1h/slide/21.png"
  - "@scenes/slide/report-minutes-5w1h/slide/22.png"
  - "@scenes/slide/report-minutes-5w1h/slide/23.png"
  - "@scenes/slide/report-minutes-5w1h/slide/24.png"
  - "@scenes/slide/report-minutes-5w1h/slide/25.png"
  - "@scenes/slide/report-minutes-5w1h/slide/26.png"
  - "@scenes/slide/report-minutes-5w1h/slide/27.png"
  - "@scenes/slide/report-minutes-5w1h/slide/28.png"
  - "@scenes/slide/report-minutes-5w1h/slide/29.png"
  - "@scenes/slide/report-minutes-5w1h/slide/30.png"
  - "@scenes/slide/report-minutes-5w1h/slide/31.png"
  - "@scenes/slide/report-minutes-5w1h/slide/32.png"
  - "@scenes/slide/report-minutes-5w1h/slide/33.png"
  - "@scenes/slide/report-minutes-5w1h/slide/34.png"
  - "@scenes/slide/report-minutes-5w1h/slide/35.png"
  - "@scenes/slide/report-minutes-5w1h/slide/36.png"
  - "@scenes/slide/report-minutes-5w1h/slide/37.png"
  - "@scenes/slide/report-minutes-5w1h/slide/38.png"
  - "@scenes/slide/report-minutes-5w1h/slide/39.png"
  - "@scenes/slide/report-minutes-5w1h/slide/40.png"
  - "@scenes/slide/report-minutes-5w1h/slide/41.png"
  - "@scenes/slide/report-minutes-5w1h/slide/42.png"
  - "@scenes/slide/report-minutes-5w1h/slide/43.png"
  - "@scenes/slide/report-minutes-5w1h/slide/44.png"
  - "@scenes/slide/report-minutes-5w1h/slide/45.png"
  - "@scenes/slide/report-minutes-5w1h/slide/46.png"
  - "@scenes/slide/report-minutes-5w1h/slide/47.png"
  - "@scenes/slide/report-minutes-5w1h/slide/48.png"
  - "@scenes/slide/report-minutes-5w1h/slide/49.png"
  - "@scenes/slide/report-minutes-5w1h/slide/50.png"
  - "@scenes/slide/report-minutes-5w1h/slide/51.png"
  - "@scenes/slide/report-minutes-5w1h/slide/52.png"
  - "@scenes/slide/report-minutes-5w1h/slide/53.png"
  - "@scenes/slide/report-minutes-5w1h/slide/54.png"
  - "@scenes/slide/report-minutes-5w1h/slide/55.png"
  - "@scenes/slide/report-minutes-5w1h/slide/56.png"
  - "@scenes/slide/report-minutes-5w1h/slide/57.png"
