title: 先読み力と「気づく力」を鍛える
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-foresight/slide/1.png"
  - "@scenes/slide/workskill02-foresight/slide/2.png"
  - "@scenes/slide/workskill02-foresight/slide/3.png"
  - "@scenes/slide/workskill02-foresight/slide/4.png"
  - "@scenes/slide/workskill02-foresight/slide/5.png"
  - "@scenes/slide/workskill02-foresight/slide/6.png"
  - "@scenes/slide/workskill02-foresight/slide/7.png"
  - "@scenes/slide/workskill02-foresight/slide/8.png"
  - "@scenes/slide/workskill02-foresight/slide/9.png"
  - "@scenes/slide/workskill02-foresight/slide/10.png"
  - "@scenes/slide/workskill02-foresight/slide/11.png"
  - "@scenes/slide/workskill02-foresight/slide/12.png"
  - "@scenes/slide/workskill02-foresight/slide/13.png"
  - "@scenes/slide/workskill02-foresight/slide/14.png"
  - "@scenes/slide/workskill02-foresight/slide/15.png"
  - "@scenes/slide/workskill02-foresight/slide/16.png"
  - "@scenes/slide/workskill02-foresight/slide/17.png"
  - "@scenes/slide/workskill02-foresight/slide/18.png"
  - "@scenes/slide/workskill02-foresight/slide/19.png"
  - "@scenes/slide/workskill02-foresight/slide/20.png"
  - "@scenes/slide/workskill02-foresight/slide/21.png"
  - "@scenes/slide/workskill02-foresight/slide/22.png"
