title: 先読み力と「気づく力」を鍛える
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-foresight/slide/1.jpg"
  - "@scenes/slide/workskill02-foresight/slide/2.jpg"
  - "@scenes/slide/workskill02-foresight/slide/3.jpg"
  - "@scenes/slide/workskill02-foresight/slide/4.jpg"
  - "@scenes/slide/workskill02-foresight/slide/5.jpg"
  - "@scenes/slide/workskill02-foresight/slide/6.jpg"
  - "@scenes/slide/workskill02-foresight/slide/7.jpg"
  - "@scenes/slide/workskill02-foresight/slide/8.jpg"
  - "@scenes/slide/workskill02-foresight/slide/9.jpg"
  - "@scenes/slide/workskill02-foresight/slide/10.jpg"
  - "@scenes/slide/workskill02-foresight/slide/11.jpg"
  - "@scenes/slide/workskill02-foresight/slide/12.jpg"
  - "@scenes/slide/workskill02-foresight/slide/13.jpg"
  - "@scenes/slide/workskill02-foresight/slide/14.jpg"
  - "@scenes/slide/workskill02-foresight/slide/15.jpg"
  - "@scenes/slide/workskill02-foresight/slide/16.jpg"
  - "@scenes/slide/workskill02-foresight/slide/17.jpg"
  - "@scenes/slide/workskill02-foresight/slide/18.jpg"
  - "@scenes/slide/workskill02-foresight/slide/19.jpg"
  - "@scenes/slide/workskill02-foresight/slide/20.jpg"
  - "@scenes/slide/workskill02-foresight/slide/21.jpg"
  - "@scenes/slide/workskill02-foresight/slide/22.jpg"
