title: 先読み力と「気づく力」を鍛える
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill02-foresight/slide/1.png"
  - "@scenes/slide/workskill02-foresight/slide/2.png"
  - "@scenes/slide/workskill02-foresight/slide/3.png"
  - "@scenes/slide/workskill02-foresight/slide/4.png"
  - "@scenes/slide/workskill02-foresight/slide/5.png"
  - "@scenes/slide/workskill02-foresight/slide/6.png"
  - "@scenes/slide/workskill02-foresight/slide/7.png"
  - "@scenes/slide/workskill02-foresight/slide/8.png"
  - "@scenes/slide/workskill02-foresight/slide/9.png"
  - "@scenes/slide/workskill02-foresight/slide/10.png"
  - "@scenes/slide/workskill02-foresight/slide/11.png"
  - "@scenes/slide/workskill02-foresight/slide/12.png"
  - "@scenes/slide/workskill02-foresight/slide/13.png"
  - "@scenes/slide/workskill02-foresight/slide/14.png"
  - "@scenes/slide/workskill02-foresight/slide/15.png"
  - "@scenes/slide/workskill02-foresight/slide/16.png"
  - "@scenes/slide/workskill02-foresight/slide/17.png"
  - "@scenes/slide/workskill02-foresight/slide/18.png"
  - "@scenes/slide/workskill02-foresight/slide/19.png"
  - "@scenes/slide/workskill02-foresight/slide/20.png"
  - "@scenes/slide/workskill02-foresight/slide/21.png"
  - "@scenes/slide/workskill02-foresight/slide/22.png"
  - "@scenes/slide/workskill02-foresight/slide/23.png"
  - "@scenes/slide/workskill02-foresight/slide/24.png"
  - "@scenes/slide/workskill02-foresight/slide/25.png"
  - "@scenes/slide/workskill02-foresight/slide/26.png"
  - "@scenes/slide/workskill02-foresight/slide/27.png"
  - "@scenes/slide/workskill02-foresight/slide/28.png"
  - "@scenes/slide/workskill02-foresight/slide/29.png"
  - "@scenes/slide/workskill02-foresight/slide/30.png"
  - "@scenes/slide/workskill02-foresight/slide/31.png"
  - "@scenes/slide/workskill02-foresight/slide/32.png"
  - "@scenes/slide/workskill02-foresight/slide/33.png"
  - "@scenes/slide/workskill02-foresight/slide/34.png"
  - "@scenes/slide/workskill02-foresight/slide/35.png"
  - "@scenes/slide/workskill02-foresight/slide/36.png"
  - "@scenes/slide/workskill02-foresight/slide/37.png"
  - "@scenes/slide/workskill02-foresight/slide/38.png"
  - "@scenes/slide/workskill02-foresight/slide/39.png"
  - "@scenes/slide/workskill02-foresight/slide/40.png"
  - "@scenes/slide/workskill02-foresight/slide/41.png"
  - "@scenes/slide/workskill02-foresight/slide/42.png"
  - "@scenes/slide/workskill02-foresight/slide/43.png"
  - "@scenes/slide/workskill02-foresight/slide/44.png"
