title: Dễ hiểu! Nhập môn Logistics Ⅰ UNIT2
btn_next_scene_name: Tiếp theo
slide_speed: 10
img:
  - "@scenes/slide/vi-logistics01-unit02/slide/1.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/2.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/3.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/4.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/5.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/6.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/7.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/8.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/9.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/10.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/11.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/12.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/13.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/14.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/15.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/16.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/17.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/18.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/19.png"
  - "@scenes/slide/vi-logistics01-unit02/slide/20.png"
