title: セクハラの定義と種類
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-sexual-def/slide/1.jpg"
  - "@scenes/slide/harass-sexual-def/slide/2.jpg"
  - "@scenes/slide/harass-sexual-def/slide/3.jpg"
  - "@scenes/slide/harass-sexual-def/slide/4.jpg"
  - "@scenes/slide/harass-sexual-def/slide/5.jpg"
  - "@scenes/slide/harass-sexual-def/slide/6.jpg"
  - "@scenes/slide/harass-sexual-def/slide/7.jpg"
  - "@scenes/slide/harass-sexual-def/slide/8.jpg"
  - "@scenes/slide/harass-sexual-def/slide/9.jpg"
  - "@scenes/slide/harass-sexual-def/slide/10.jpg"
  - "@scenes/slide/harass-sexual-def/slide/11.jpg"
  - "@scenes/slide/harass-sexual-def/slide/12.jpg"
  - "@scenes/slide/harass-sexual-def/slide/13.jpg"
  - "@scenes/slide/harass-sexual-def/slide/14.jpg"
  - "@scenes/slide/harass-sexual-def/slide/15.jpg"
  - "@scenes/slide/harass-sexual-def/slide/16.jpg"
  - "@scenes/slide/harass-sexual-def/slide/17.jpg"
  - "@scenes/slide/harass-sexual-def/slide/18.jpg"
  - "@scenes/slide/harass-sexual-def/slide/19.jpg"
  - "@scenes/slide/harass-sexual-def/slide/20.jpg"
  - "@scenes/slide/harass-sexual-def/slide/21.jpg"
  - "@scenes/slide/harass-sexual-def/slide/22.jpg"
  - "@scenes/slide/harass-sexual-def/slide/23.jpg"
  - "@scenes/slide/harass-sexual-def/slide/24.jpg"
