title: 人脈と信頼ネットワークの築き方
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-network/slide/1.png"
  - "@scenes/slide/workskill03-network/slide/2.png"
  - "@scenes/slide/workskill03-network/slide/3.png"
  - "@scenes/slide/workskill03-network/slide/4.png"
  - "@scenes/slide/workskill03-network/slide/5.png"
  - "@scenes/slide/workskill03-network/slide/6.png"
  - "@scenes/slide/workskill03-network/slide/7.png"
  - "@scenes/slide/workskill03-network/slide/8.png"
  - "@scenes/slide/workskill03-network/slide/9.png"
  - "@scenes/slide/workskill03-network/slide/10.png"
  - "@scenes/slide/workskill03-network/slide/11.png"
  - "@scenes/slide/workskill03-network/slide/12.png"
  - "@scenes/slide/workskill03-network/slide/13.png"
  - "@scenes/slide/workskill03-network/slide/14.png"
  - "@scenes/slide/workskill03-network/slide/15.png"
  - "@scenes/slide/workskill03-network/slide/16.png"
  - "@scenes/slide/workskill03-network/slide/17.png"
  - "@scenes/slide/workskill03-network/slide/18.png"
  - "@scenes/slide/workskill03-network/slide/19.png"
  - "@scenes/slide/workskill03-network/slide/20.png"
  - "@scenes/slide/workskill03-network/slide/21.png"
  - "@scenes/slide/workskill03-network/slide/22.png"
