title: 防止のための行動指針と職場の義務
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-power-action/slide/1.jpg"
  - "@scenes/slide/harass-power-action/slide/2.jpg"
  - "@scenes/slide/harass-power-action/slide/3.jpg"
  - "@scenes/slide/harass-power-action/slide/4.jpg"
  - "@scenes/slide/harass-power-action/slide/5.jpg"
  - "@scenes/slide/harass-power-action/slide/6.jpg"
  - "@scenes/slide/harass-power-action/slide/7.jpg"
  - "@scenes/slide/harass-power-action/slide/8.jpg"
  - "@scenes/slide/harass-power-action/slide/9.jpg"
  - "@scenes/slide/harass-power-action/slide/10.jpg"
  - "@scenes/slide/harass-power-action/slide/11.jpg"
  - "@scenes/slide/harass-power-action/slide/12.jpg"
  - "@scenes/slide/harass-power-action/slide/13.jpg"
  - "@scenes/slide/harass-power-action/slide/14.jpg"
  - "@scenes/slide/harass-power-action/slide/15.jpg"
  - "@scenes/slide/harass-power-action/slide/16.jpg"
  - "@scenes/slide/harass-power-action/slide/17.jpg"
  - "@scenes/slide/harass-power-action/slide/18.jpg"
  - "@scenes/slide/harass-power-action/slide/19.jpg"
  - "@scenes/slide/harass-power-action/slide/20.jpg"
  - "@scenes/slide/harass-power-action/slide/21.jpg"
  - "@scenes/slide/harass-power-action/slide/22.jpg"
  - "@scenes/slide/harass-power-action/slide/23.jpg"
  - "@scenes/slide/harass-power-action/slide/24.jpg"
  - "@scenes/slide/harass-power-action/slide/25.jpg"
  - "@scenes/slide/harass-power-action/slide/26.jpg"
  - "@scenes/slide/harass-power-action/slide/27.jpg"
