title: 正確な聞き取りと復唱
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-phone-listening/slide/1.png"
  - "@scenes/slide/call-phone-listening/slide/2.png"
  - "@scenes/slide/call-phone-listening/slide/3.png"
  - "@scenes/slide/call-phone-listening/slide/4.png"
  - "@scenes/slide/call-phone-listening/slide/5.png"
  - "@scenes/slide/call-phone-listening/slide/6.png"
  - "@scenes/slide/call-phone-listening/slide/7.png"
  - "@scenes/slide/call-phone-listening/slide/8.png"
  - "@scenes/slide/call-phone-listening/slide/9.png"
  - "@scenes/slide/call-phone-listening/slide/10.png"
  - "@scenes/slide/call-phone-listening/slide/11.png"
  - "@scenes/slide/call-phone-listening/slide/12.png"
  - "@scenes/slide/call-phone-listening/slide/13.png"
  - "@scenes/slide/call-phone-listening/slide/14.png"
  - "@scenes/slide/call-phone-listening/slide/15.png"
  - "@scenes/slide/call-phone-listening/slide/16.png"
  - "@scenes/slide/call-phone-listening/slide/17.png"
  - "@scenes/slide/call-phone-listening/slide/18.png"
  - "@scenes/slide/call-phone-listening/slide/19.png"
  - "@scenes/slide/call-phone-listening/slide/20.png"
  - "@scenes/slide/call-phone-listening/slide/21.png"
  - "@scenes/slide/call-phone-listening/slide/22.png"
  - "@scenes/slide/call-phone-listening/slide/23.png"
  - "@scenes/slide/call-phone-listening/slide/24.png"
  - "@scenes/slide/call-phone-listening/slide/25.png"
  - "@scenes/slide/call-phone-listening/slide/26.png"
  - "@scenes/slide/call-phone-listening/slide/27.png"
  - "@scenes/slide/call-phone-listening/slide/28.png"
  - "@scenes/slide/call-phone-listening/slide/29.png"
  - "@scenes/slide/call-phone-listening/slide/30.png"
  - "@scenes/slide/call-phone-listening/slide/31.png"
  - "@scenes/slide/call-phone-listening/slide/32.png"
  - "@scenes/slide/call-phone-listening/slide/33.png"
  - "@scenes/slide/call-phone-listening/slide/34.png"
  - "@scenes/slide/call-phone-listening/slide/35.png"
  - "@scenes/slide/call-phone-listening/slide/36.png"
  - "@scenes/slide/call-phone-listening/slide/37.png"
  - "@scenes/slide/call-phone-listening/slide/38.png"
  - "@scenes/slide/call-phone-listening/slide/39.png"
  - "@scenes/slide/call-phone-listening/slide/40.png"
  - "@scenes/slide/call-phone-listening/slide/41.png"
  - "@scenes/slide/call-phone-listening/slide/42.png"
  - "@scenes/slide/call-phone-listening/slide/43.png"
  - "@scenes/slide/call-phone-listening/slide/44.png"
  - "@scenes/slide/call-phone-listening/slide/45.png"
  - "@scenes/slide/call-phone-listening/slide/46.png"
  - "@scenes/slide/call-phone-listening/slide/47.png"
  - "@scenes/slide/call-phone-listening/slide/48.png"
  - "@scenes/slide/call-phone-listening/slide/49.png"
  - "@scenes/slide/call-phone-listening/slide/50.png"
  - "@scenes/slide/call-phone-listening/slide/51.png"
  - "@scenes/slide/call-phone-listening/slide/52.png"
  - "@scenes/slide/call-phone-listening/slide/53.png"
  - "@scenes/slide/call-phone-listening/slide/54.png"
  - "@scenes/slide/call-phone-listening/slide/55.png"
  - "@scenes/slide/call-phone-listening/slide/56.png"
