title: 正確な聞き取りと復唱
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-phone-listening/slide/1.jpg"
  - "@scenes/slide/call-phone-listening/slide/2.jpg"
  - "@scenes/slide/call-phone-listening/slide/3.jpg"
  - "@scenes/slide/call-phone-listening/slide/4.jpg"
  - "@scenes/slide/call-phone-listening/slide/5.jpg"
  - "@scenes/slide/call-phone-listening/slide/6.jpg"
  - "@scenes/slide/call-phone-listening/slide/7.jpg"
  - "@scenes/slide/call-phone-listening/slide/8.jpg"
  - "@scenes/slide/call-phone-listening/slide/9.jpg"
  - "@scenes/slide/call-phone-listening/slide/10.jpg"
  - "@scenes/slide/call-phone-listening/slide/11.jpg"
  - "@scenes/slide/call-phone-listening/slide/12.jpg"
  - "@scenes/slide/call-phone-listening/slide/13.jpg"
  - "@scenes/slide/call-phone-listening/slide/14.jpg"
  - "@scenes/slide/call-phone-listening/slide/15.jpg"
  - "@scenes/slide/call-phone-listening/slide/16.jpg"
  - "@scenes/slide/call-phone-listening/slide/17.jpg"
  - "@scenes/slide/call-phone-listening/slide/18.jpg"
  - "@scenes/slide/call-phone-listening/slide/19.jpg"
  - "@scenes/slide/call-phone-listening/slide/20.jpg"
  - "@scenes/slide/call-phone-listening/slide/21.jpg"
  - "@scenes/slide/call-phone-listening/slide/22.jpg"
  - "@scenes/slide/call-phone-listening/slide/23.jpg"
  - "@scenes/slide/call-phone-listening/slide/24.jpg"
  - "@scenes/slide/call-phone-listening/slide/25.jpg"
  - "@scenes/slide/call-phone-listening/slide/26.jpg"
  - "@scenes/slide/call-phone-listening/slide/27.jpg"
  - "@scenes/slide/call-phone-listening/slide/28.jpg"
  - "@scenes/slide/call-phone-listening/slide/29.jpg"
  - "@scenes/slide/call-phone-listening/slide/30.jpg"
  - "@scenes/slide/call-phone-listening/slide/31.jpg"
  - "@scenes/slide/call-phone-listening/slide/32.jpg"
  - "@scenes/slide/call-phone-listening/slide/33.jpg"
  - "@scenes/slide/call-phone-listening/slide/34.jpg"
  - "@scenes/slide/call-phone-listening/slide/35.jpg"
  - "@scenes/slide/call-phone-listening/slide/36.jpg"
  - "@scenes/slide/call-phone-listening/slide/37.jpg"
  - "@scenes/slide/call-phone-listening/slide/38.jpg"
  - "@scenes/slide/call-phone-listening/slide/39.jpg"
  - "@scenes/slide/call-phone-listening/slide/40.jpg"
  - "@scenes/slide/call-phone-listening/slide/41.jpg"
  - "@scenes/slide/call-phone-listening/slide/42.jpg"
  - "@scenes/slide/call-phone-listening/slide/43.jpg"
  - "@scenes/slide/call-phone-listening/slide/44.jpg"
  - "@scenes/slide/call-phone-listening/slide/45.jpg"
  - "@scenes/slide/call-phone-listening/slide/46.jpg"
  - "@scenes/slide/call-phone-listening/slide/47.jpg"
  - "@scenes/slide/call-phone-listening/slide/48.jpg"
  - "@scenes/slide/call-phone-listening/slide/49.jpg"
  - "@scenes/slide/call-phone-listening/slide/50.jpg"
  - "@scenes/slide/call-phone-listening/slide/51.jpg"
  - "@scenes/slide/call-phone-listening/slide/52.jpg"
  - "@scenes/slide/call-phone-listening/slide/53.jpg"
  - "@scenes/slide/call-phone-listening/slide/54.jpg"
  - "@scenes/slide/call-phone-listening/slide/55.jpg"
  - "@scenes/slide/call-phone-listening/slide/56.jpg"
