title: エスカレーション判断と自己のメンタルケア
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-claim-escalation/slide/1.png"
  - "@scenes/slide/call-claim-escalation/slide/2.png"
  - "@scenes/slide/call-claim-escalation/slide/3.png"
  - "@scenes/slide/call-claim-escalation/slide/4.png"
  - "@scenes/slide/call-claim-escalation/slide/5.png"
  - "@scenes/slide/call-claim-escalation/slide/6.png"
  - "@scenes/slide/call-claim-escalation/slide/7.png"
  - "@scenes/slide/call-claim-escalation/slide/8.png"
  - "@scenes/slide/call-claim-escalation/slide/9.png"
  - "@scenes/slide/call-claim-escalation/slide/10.png"
  - "@scenes/slide/call-claim-escalation/slide/11.png"
  - "@scenes/slide/call-claim-escalation/slide/12.png"
  - "@scenes/slide/call-claim-escalation/slide/13.png"
  - "@scenes/slide/call-claim-escalation/slide/14.png"
  - "@scenes/slide/call-claim-escalation/slide/15.png"
  - "@scenes/slide/call-claim-escalation/slide/16.png"
  - "@scenes/slide/call-claim-escalation/slide/17.png"
  - "@scenes/slide/call-claim-escalation/slide/18.png"
  - "@scenes/slide/call-claim-escalation/slide/19.png"
  - "@scenes/slide/call-claim-escalation/slide/20.png"
  - "@scenes/slide/call-claim-escalation/slide/21.png"
  - "@scenes/slide/call-claim-escalation/slide/22.png"
  - "@scenes/slide/call-claim-escalation/slide/23.png"
  - "@scenes/slide/call-claim-escalation/slide/24.png"
  - "@scenes/slide/call-claim-escalation/slide/25.png"
  - "@scenes/slide/call-claim-escalation/slide/26.png"
  - "@scenes/slide/call-claim-escalation/slide/27.png"
  - "@scenes/slide/call-claim-escalation/slide/28.png"
  - "@scenes/slide/call-claim-escalation/slide/29.png"
  - "@scenes/slide/call-claim-escalation/slide/30.png"
  - "@scenes/slide/call-claim-escalation/slide/31.png"
  - "@scenes/slide/call-claim-escalation/slide/32.png"
  - "@scenes/slide/call-claim-escalation/slide/33.png"
  - "@scenes/slide/call-claim-escalation/slide/34.png"
  - "@scenes/slide/call-claim-escalation/slide/35.png"
  - "@scenes/slide/call-claim-escalation/slide/36.png"
  - "@scenes/slide/call-claim-escalation/slide/37.png"
  - "@scenes/slide/call-claim-escalation/slide/38.png"
  - "@scenes/slide/call-claim-escalation/slide/39.png"
  - "@scenes/slide/call-claim-escalation/slide/40.png"
  - "@scenes/slide/call-claim-escalation/slide/41.png"
  - "@scenes/slide/call-claim-escalation/slide/42.png"
  - "@scenes/slide/call-claim-escalation/slide/43.png"
  - "@scenes/slide/call-claim-escalation/slide/44.png"
  - "@scenes/slide/call-claim-escalation/slide/45.png"
  - "@scenes/slide/call-claim-escalation/slide/46.png"
  - "@scenes/slide/call-claim-escalation/slide/47.png"
  - "@scenes/slide/call-claim-escalation/slide/48.png"
  - "@scenes/slide/call-claim-escalation/slide/49.png"
  - "@scenes/slide/call-claim-escalation/slide/50.png"
  - "@scenes/slide/call-claim-escalation/slide/51.png"
  - "@scenes/slide/call-claim-escalation/slide/52.png"
  - "@scenes/slide/call-claim-escalation/slide/53.png"
  - "@scenes/slide/call-claim-escalation/slide/54.png"
  - "@scenes/slide/call-claim-escalation/slide/55.png"
  - "@scenes/slide/call-claim-escalation/slide/56.png"
  - "@scenes/slide/call-claim-escalation/slide/57.png"
  - "@scenes/slide/call-claim-escalation/slide/58.png"
  - "@scenes/slide/call-claim-escalation/slide/59.png"
