title: エスカレーション判断と自己のメンタルケア
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-claim-escalation/slide/1.jpg"
  - "@scenes/slide/call-claim-escalation/slide/2.jpg"
  - "@scenes/slide/call-claim-escalation/slide/3.jpg"
  - "@scenes/slide/call-claim-escalation/slide/4.jpg"
  - "@scenes/slide/call-claim-escalation/slide/5.jpg"
  - "@scenes/slide/call-claim-escalation/slide/6.jpg"
  - "@scenes/slide/call-claim-escalation/slide/7.jpg"
  - "@scenes/slide/call-claim-escalation/slide/8.jpg"
  - "@scenes/slide/call-claim-escalation/slide/9.jpg"
  - "@scenes/slide/call-claim-escalation/slide/10.jpg"
  - "@scenes/slide/call-claim-escalation/slide/11.jpg"
  - "@scenes/slide/call-claim-escalation/slide/12.jpg"
  - "@scenes/slide/call-claim-escalation/slide/13.jpg"
  - "@scenes/slide/call-claim-escalation/slide/14.jpg"
  - "@scenes/slide/call-claim-escalation/slide/15.jpg"
  - "@scenes/slide/call-claim-escalation/slide/16.jpg"
  - "@scenes/slide/call-claim-escalation/slide/17.jpg"
  - "@scenes/slide/call-claim-escalation/slide/18.jpg"
  - "@scenes/slide/call-claim-escalation/slide/19.jpg"
  - "@scenes/slide/call-claim-escalation/slide/20.jpg"
  - "@scenes/slide/call-claim-escalation/slide/21.jpg"
  - "@scenes/slide/call-claim-escalation/slide/22.jpg"
  - "@scenes/slide/call-claim-escalation/slide/23.jpg"
  - "@scenes/slide/call-claim-escalation/slide/24.jpg"
  - "@scenes/slide/call-claim-escalation/slide/25.jpg"
  - "@scenes/slide/call-claim-escalation/slide/26.jpg"
  - "@scenes/slide/call-claim-escalation/slide/27.jpg"
  - "@scenes/slide/call-claim-escalation/slide/28.jpg"
  - "@scenes/slide/call-claim-escalation/slide/29.jpg"
  - "@scenes/slide/call-claim-escalation/slide/30.jpg"
