title: 時間管理と生活リズムの整え方
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-time-management/slide/1.jpg"
  - "@scenes/slide/workskill01-time-management/slide/2.jpg"
  - "@scenes/slide/workskill01-time-management/slide/3.jpg"
  - "@scenes/slide/workskill01-time-management/slide/4.jpg"
  - "@scenes/slide/workskill01-time-management/slide/5.jpg"
  - "@scenes/slide/workskill01-time-management/slide/6.jpg"
  - "@scenes/slide/workskill01-time-management/slide/7.jpg"
  - "@scenes/slide/workskill01-time-management/slide/8.jpg"
  - "@scenes/slide/workskill01-time-management/slide/9.jpg"
  - "@scenes/slide/workskill01-time-management/slide/10.jpg"
  - "@scenes/slide/workskill01-time-management/slide/11.jpg"
  - "@scenes/slide/workskill01-time-management/slide/12.jpg"
  - "@scenes/slide/workskill01-time-management/slide/13.jpg"
  - "@scenes/slide/workskill01-time-management/slide/14.jpg"
  - "@scenes/slide/workskill01-time-management/slide/15.jpg"
  - "@scenes/slide/workskill01-time-management/slide/16.jpg"
  - "@scenes/slide/workskill01-time-management/slide/17.jpg"
  - "@scenes/slide/workskill01-time-management/slide/18.jpg"
  - "@scenes/slide/workskill01-time-management/slide/19.jpg"
  - "@scenes/slide/workskill01-time-management/slide/20.jpg"
  - "@scenes/slide/workskill01-time-management/slide/21.jpg"
  - "@scenes/slide/workskill01-time-management/slide/22.jpg"
