title: 信頼関係の構築と自己成長の振り返り
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-trust-growth/slide/1.png"
  - "@scenes/slide/workskill01-trust-growth/slide/2.png"
  - "@scenes/slide/workskill01-trust-growth/slide/3.png"
  - "@scenes/slide/workskill01-trust-growth/slide/4.png"
  - "@scenes/slide/workskill01-trust-growth/slide/5.png"
  - "@scenes/slide/workskill01-trust-growth/slide/6.png"
  - "@scenes/slide/workskill01-trust-growth/slide/7.png"
  - "@scenes/slide/workskill01-trust-growth/slide/8.png"
  - "@scenes/slide/workskill01-trust-growth/slide/9.png"
  - "@scenes/slide/workskill01-trust-growth/slide/10.png"
  - "@scenes/slide/workskill01-trust-growth/slide/11.png"
  - "@scenes/slide/workskill01-trust-growth/slide/12.png"
  - "@scenes/slide/workskill01-trust-growth/slide/13.png"
  - "@scenes/slide/workskill01-trust-growth/slide/14.png"
  - "@scenes/slide/workskill01-trust-growth/slide/15.png"
  - "@scenes/slide/workskill01-trust-growth/slide/16.png"
  - "@scenes/slide/workskill01-trust-growth/slide/17.png"
  - "@scenes/slide/workskill01-trust-growth/slide/18.png"
  - "@scenes/slide/workskill01-trust-growth/slide/19.png"
  - "@scenes/slide/workskill01-trust-growth/slide/20.png"
  - "@scenes/slide/workskill01-trust-growth/slide/21.png"
  - "@scenes/slide/workskill01-trust-growth/slide/22.png"
  - "@scenes/slide/workskill01-trust-growth/slide/23.png"
  - "@scenes/slide/workskill01-trust-growth/slide/24.png"
  - "@scenes/slide/workskill01-trust-growth/slide/25.png"
  - "@scenes/slide/workskill01-trust-growth/slide/26.png"
  - "@scenes/slide/workskill01-trust-growth/slide/27.png"
  - "@scenes/slide/workskill01-trust-growth/slide/28.png"
  - "@scenes/slide/workskill01-trust-growth/slide/29.png"
  - "@scenes/slide/workskill01-trust-growth/slide/30.png"
  - "@scenes/slide/workskill01-trust-growth/slide/31.png"
  - "@scenes/slide/workskill01-trust-growth/slide/32.png"
  - "@scenes/slide/workskill01-trust-growth/slide/33.png"
  - "@scenes/slide/workskill01-trust-growth/slide/34.png"
  - "@scenes/slide/workskill01-trust-growth/slide/35.png"
  - "@scenes/slide/workskill01-trust-growth/slide/36.png"
  - "@scenes/slide/workskill01-trust-growth/slide/37.png"
  - "@scenes/slide/workskill01-trust-growth/slide/38.png"
  - "@scenes/slide/workskill01-trust-growth/slide/39.png"
  - "@scenes/slide/workskill01-trust-growth/slide/40.png"
  - "@scenes/slide/workskill01-trust-growth/slide/41.png"
  - "@scenes/slide/workskill01-trust-growth/slide/42.png"
  - "@scenes/slide/workskill01-trust-growth/slide/43.png"
  - "@scenes/slide/workskill01-trust-growth/slide/44.png"
