title: 信頼関係の構築と自己成長の振り返り
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-trust-growth/slide/1.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/2.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/3.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/4.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/5.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/6.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/7.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/8.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/9.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/10.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/11.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/12.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/13.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/14.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/15.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/16.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/17.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/18.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/19.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/20.jpg"
  - "@scenes/slide/workskill01-trust-growth/slide/21.jpg"
