title: 信頼関係の構築と自己成長の振り返り
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-trust-growth/slide/1.png"
  - "@scenes/slide/workskill01-trust-growth/slide/2.png"
  - "@scenes/slide/workskill01-trust-growth/slide/3.png"
  - "@scenes/slide/workskill01-trust-growth/slide/4.png"
  - "@scenes/slide/workskill01-trust-growth/slide/5.png"
  - "@scenes/slide/workskill01-trust-growth/slide/6.png"
  - "@scenes/slide/workskill01-trust-growth/slide/7.png"
  - "@scenes/slide/workskill01-trust-growth/slide/8.png"
  - "@scenes/slide/workskill01-trust-growth/slide/9.png"
  - "@scenes/slide/workskill01-trust-growth/slide/10.png"
  - "@scenes/slide/workskill01-trust-growth/slide/11.png"
  - "@scenes/slide/workskill01-trust-growth/slide/12.png"
  - "@scenes/slide/workskill01-trust-growth/slide/13.png"
  - "@scenes/slide/workskill01-trust-growth/slide/14.png"
  - "@scenes/slide/workskill01-trust-growth/slide/15.png"
  - "@scenes/slide/workskill01-trust-growth/slide/16.png"
  - "@scenes/slide/workskill01-trust-growth/slide/17.png"
  - "@scenes/slide/workskill01-trust-growth/slide/18.png"
  - "@scenes/slide/workskill01-trust-growth/slide/19.png"
  - "@scenes/slide/workskill01-trust-growth/slide/20.png"
  - "@scenes/slide/workskill01-trust-growth/slide/21.png"
