title: 報告書の構造と書き方
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/report-minutes-structure/slide/1.jpg"
  - "@scenes/slide/report-minutes-structure/slide/2.jpg"
  - "@scenes/slide/report-minutes-structure/slide/3.jpg"
  - "@scenes/slide/report-minutes-structure/slide/4.jpg"
  - "@scenes/slide/report-minutes-structure/slide/5.jpg"
  - "@scenes/slide/report-minutes-structure/slide/6.jpg"
  - "@scenes/slide/report-minutes-structure/slide/7.jpg"
  - "@scenes/slide/report-minutes-structure/slide/8.jpg"
  - "@scenes/slide/report-minutes-structure/slide/9.jpg"
  - "@scenes/slide/report-minutes-structure/slide/10.jpg"
  - "@scenes/slide/report-minutes-structure/slide/11.jpg"
  - "@scenes/slide/report-minutes-structure/slide/12.jpg"
  - "@scenes/slide/report-minutes-structure/slide/13.jpg"
  - "@scenes/slide/report-minutes-structure/slide/14.jpg"
  - "@scenes/slide/report-minutes-structure/slide/15.jpg"
  - "@scenes/slide/report-minutes-structure/slide/16.jpg"
  - "@scenes/slide/report-minutes-structure/slide/17.jpg"
  - "@scenes/slide/report-minutes-structure/slide/18.jpg"
  - "@scenes/slide/report-minutes-structure/slide/19.jpg"
  - "@scenes/slide/report-minutes-structure/slide/20.jpg"
  - "@scenes/slide/report-minutes-structure/slide/21.jpg"
  - "@scenes/slide/report-minutes-structure/slide/22.jpg"
  - "@scenes/slide/report-minutes-structure/slide/23.jpg"
  - "@scenes/slide/report-minutes-structure/slide/24.jpg"
  - "@scenes/slide/report-minutes-structure/slide/25.jpg"
  - "@scenes/slide/report-minutes-structure/slide/26.jpg"
