title: 報告書の構造と書き方
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/report-minutes-structure/slide/1.png"
  - "@scenes/slide/report-minutes-structure/slide/2.png"
  - "@scenes/slide/report-minutes-structure/slide/3.png"
  - "@scenes/slide/report-minutes-structure/slide/4.png"
  - "@scenes/slide/report-minutes-structure/slide/5.png"
  - "@scenes/slide/report-minutes-structure/slide/6.png"
  - "@scenes/slide/report-minutes-structure/slide/7.png"
  - "@scenes/slide/report-minutes-structure/slide/8.png"
  - "@scenes/slide/report-minutes-structure/slide/9.png"
  - "@scenes/slide/report-minutes-structure/slide/10.png"
  - "@scenes/slide/report-minutes-structure/slide/11.png"
  - "@scenes/slide/report-minutes-structure/slide/12.png"
  - "@scenes/slide/report-minutes-structure/slide/13.png"
  - "@scenes/slide/report-minutes-structure/slide/14.png"
  - "@scenes/slide/report-minutes-structure/slide/15.png"
  - "@scenes/slide/report-minutes-structure/slide/16.png"
  - "@scenes/slide/report-minutes-structure/slide/17.png"
  - "@scenes/slide/report-minutes-structure/slide/18.png"
  - "@scenes/slide/report-minutes-structure/slide/19.png"
  - "@scenes/slide/report-minutes-structure/slide/20.png"
  - "@scenes/slide/report-minutes-structure/slide/21.png"
  - "@scenes/slide/report-minutes-structure/slide/22.png"
  - "@scenes/slide/report-minutes-structure/slide/23.png"
  - "@scenes/slide/report-minutes-structure/slide/24.png"
  - "@scenes/slide/report-minutes-structure/slide/25.png"
  - "@scenes/slide/report-minutes-structure/slide/26.png"
  - "@scenes/slide/report-minutes-structure/slide/27.png"
  - "@scenes/slide/report-minutes-structure/slide/28.png"
  - "@scenes/slide/report-minutes-structure/slide/29.png"
  - "@scenes/slide/report-minutes-structure/slide/30.png"
  - "@scenes/slide/report-minutes-structure/slide/31.png"
  - "@scenes/slide/report-minutes-structure/slide/32.png"
  - "@scenes/slide/report-minutes-structure/slide/33.png"
  - "@scenes/slide/report-minutes-structure/slide/34.png"
  - "@scenes/slide/report-minutes-structure/slide/35.png"
  - "@scenes/slide/report-minutes-structure/slide/36.png"
  - "@scenes/slide/report-minutes-structure/slide/37.png"
  - "@scenes/slide/report-minutes-structure/slide/38.png"
  - "@scenes/slide/report-minutes-structure/slide/39.png"
  - "@scenes/slide/report-minutes-structure/slide/40.png"
  - "@scenes/slide/report-minutes-structure/slide/41.png"
  - "@scenes/slide/report-minutes-structure/slide/42.png"
  - "@scenes/slide/report-minutes-structure/slide/43.png"
  - "@scenes/slide/report-minutes-structure/slide/44.png"
  - "@scenes/slide/report-minutes-structure/slide/45.png"
  - "@scenes/slide/report-minutes-structure/slide/46.png"
  - "@scenes/slide/report-minutes-structure/slide/47.png"
  - "@scenes/slide/report-minutes-structure/slide/48.png"
  - "@scenes/slide/report-minutes-structure/slide/49.png"
  - "@scenes/slide/report-minutes-structure/slide/50.png"
  - "@scenes/slide/report-minutes-structure/slide/51.png"
