title: 情報セキュリティの基礎
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/security-basics/slide/1.png"
  - "@scenes/slide/security-basics/slide/2.png"
  - "@scenes/slide/security-basics/slide/3.png"
  - "@scenes/slide/security-basics/slide/4.png"
  - "@scenes/slide/security-basics/slide/5.png"
  - "@scenes/slide/security-basics/slide/6.png"
  - "@scenes/slide/security-basics/slide/7.png"
  - "@scenes/slide/security-basics/slide/8.png"
  - "@scenes/slide/security-basics/slide/9.png"
  - "@scenes/slide/security-basics/slide/10.png"
  - "@scenes/slide/security-basics/slide/11.png"
  - "@scenes/slide/security-basics/slide/12.png"
  - "@scenes/slide/security-basics/slide/13.png"
  - "@scenes/slide/security-basics/slide/14.png"
  - "@scenes/slide/security-basics/slide/15.png"
  - "@scenes/slide/security-basics/slide/16.png"
  - "@scenes/slide/security-basics/slide/17.png"
  - "@scenes/slide/security-basics/slide/18.png"
  - "@scenes/slide/security-basics/slide/19.png"
  - "@scenes/slide/security-basics/slide/20.png"
  - "@scenes/slide/security-basics/slide/21.png"
  - "@scenes/slide/security-basics/slide/22.png"
