title: Information Security Basics
btn_next_scene_name: Next
slide_speed: 10
img:
  - "@scenes/slide/security-basics/slide/1.png"
  - "@scenes/slide/security-basics/slide/2.png"
  - "@scenes/slide/security-basics/slide/3.png"
  - "@scenes/slide/security-basics/slide/4.png"
  - "@scenes/slide/security-basics/slide/5.png"
  - "@scenes/slide/security-basics/slide/6.png"
  - "@scenes/slide/security-basics/slide/7.png"
  - "@scenes/slide/security-basics/slide/8.png"
  - "@scenes/slide/security-basics/slide/9.png"
  - "@scenes/slide/security-basics/slide/10.png"
  - "@scenes/slide/security-basics/slide/11.png"
  - "@scenes/slide/security-basics/slide/12.png"
  - "@scenes/slide/security-basics/slide/13.png"
  - "@scenes/slide/security-basics/slide/14.png"
  - "@scenes/slide/security-basics/slide/15.png"
  - "@scenes/slide/security-basics/slide/16.png"
  - "@scenes/slide/security-basics/slide/17.png"
  - "@scenes/slide/security-basics/slide/18.png"
  - "@scenes/slide/security-basics/slide/19.png"
  - "@scenes/slide/security-basics/slide/20.png"
  - "@scenes/slide/security-basics/slide/21.png"
  - "@scenes/slide/security-basics/slide/22.png"
  - "@scenes/slide/security-basics/slide/23.png"
  - "@scenes/slide/security-basics/slide/24.png"
  - "@scenes/slide/security-basics/slide/25.png"
  - "@scenes/slide/security-basics/slide/26.png"
  - "@scenes/slide/security-basics/slide/27.png"
  - "@scenes/slide/security-basics/slide/28.png"
  - "@scenes/slide/security-basics/slide/29.png"
  - "@scenes/slide/security-basics/slide/30.png"
  - "@scenes/slide/security-basics/slide/31.png"
  - "@scenes/slide/security-basics/slide/32.png"
  - "@scenes/slide/security-basics/slide/33.png"
  - "@scenes/slide/security-basics/slide/34.png"
  - "@scenes/slide/security-basics/slide/35.png"
  - "@scenes/slide/security-basics/slide/36.png"
  - "@scenes/slide/security-basics/slide/37.png"
  - "@scenes/slide/security-basics/slide/38.png"
  - "@scenes/slide/security-basics/slide/39.png"
  - "@scenes/slide/security-basics/slide/40.png"
  - "@scenes/slide/security-basics/slide/41.png"
  - "@scenes/slide/security-basics/slide/42.png"
  - "@scenes/slide/security-basics/slide/43.png"
  - "@scenes/slide/security-basics/slide/44.png"
  - "@scenes/slide/security-basics/slide/45.png"
