title: video scene title
video_url: https://p-movie.biz/player/sco1_pc/k/423d02afef72c328ce981ca5a6f267fa02aff562
complete_end_video: on
btn_next_scene_name: next scene.
btn_next_unit_name: next unit.
btn_end_unit_name: end of unit.
