title: 動画その1
video_url: https://p-movie.biz/player/sco1_pc/k/423d02afef72c328ce981ca5a6f267fa02aff562
complete_end_video: on
btn_next_scene_name: 次へ
btn_next_unit_name: 次のユニットへ
btn_end_unit_name: 終了する
