title: 学び続ける力：インプットとアウトプットの技術
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-learning/slide/1.png"
  - "@scenes/slide/workskill03-learning/slide/2.png"
  - "@scenes/slide/workskill03-learning/slide/3.png"
  - "@scenes/slide/workskill03-learning/slide/4.png"
  - "@scenes/slide/workskill03-learning/slide/5.png"
  - "@scenes/slide/workskill03-learning/slide/6.png"
  - "@scenes/slide/workskill03-learning/slide/7.png"
  - "@scenes/slide/workskill03-learning/slide/8.png"
  - "@scenes/slide/workskill03-learning/slide/9.png"
  - "@scenes/slide/workskill03-learning/slide/10.png"
  - "@scenes/slide/workskill03-learning/slide/11.png"
  - "@scenes/slide/workskill03-learning/slide/12.png"
  - "@scenes/slide/workskill03-learning/slide/13.png"
  - "@scenes/slide/workskill03-learning/slide/14.png"
  - "@scenes/slide/workskill03-learning/slide/15.png"
  - "@scenes/slide/workskill03-learning/slide/16.png"
  - "@scenes/slide/workskill03-learning/slide/17.png"
  - "@scenes/slide/workskill03-learning/slide/18.png"
  - "@scenes/slide/workskill03-learning/slide/19.png"
  - "@scenes/slide/workskill03-learning/slide/20.png"
  - "@scenes/slide/workskill03-learning/slide/21.png"
  - "@scenes/slide/workskill03-learning/slide/22.png"
  - "@scenes/slide/workskill03-learning/slide/23.png"
  - "@scenes/slide/workskill03-learning/slide/24.png"
  - "@scenes/slide/workskill03-learning/slide/25.png"
  - "@scenes/slide/workskill03-learning/slide/26.png"
  - "@scenes/slide/workskill03-learning/slide/27.png"
  - "@scenes/slide/workskill03-learning/slide/28.png"
  - "@scenes/slide/workskill03-learning/slide/29.png"
  - "@scenes/slide/workskill03-learning/slide/30.png"
  - "@scenes/slide/workskill03-learning/slide/31.png"
  - "@scenes/slide/workskill03-learning/slide/32.png"
  - "@scenes/slide/workskill03-learning/slide/33.png"
  - "@scenes/slide/workskill03-learning/slide/34.png"
  - "@scenes/slide/workskill03-learning/slide/35.png"
  - "@scenes/slide/workskill03-learning/slide/36.png"
  - "@scenes/slide/workskill03-learning/slide/37.png"
  - "@scenes/slide/workskill03-learning/slide/38.png"
  - "@scenes/slide/workskill03-learning/slide/39.png"
  - "@scenes/slide/workskill03-learning/slide/40.png"
  - "@scenes/slide/workskill03-learning/slide/41.png"
  - "@scenes/slide/workskill03-learning/slide/42.png"
  - "@scenes/slide/workskill03-learning/slide/43.png"
  - "@scenes/slide/workskill03-learning/slide/44.png"
