title: 報連相の実践力を高める
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-houkokusou/slide/1.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/2.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/3.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/4.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/5.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/6.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/7.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/8.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/9.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/10.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/11.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/12.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/13.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/14.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/15.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/16.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/17.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/18.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/19.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/20.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/21.jpg"
  - "@scenes/slide/workskill01-houkokusou/slide/22.jpg"
