title: 報連相の実践力を高める
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-houkokusou/slide/1.png"
  - "@scenes/slide/workskill01-houkokusou/slide/2.png"
  - "@scenes/slide/workskill01-houkokusou/slide/3.png"
  - "@scenes/slide/workskill01-houkokusou/slide/4.png"
  - "@scenes/slide/workskill01-houkokusou/slide/5.png"
  - "@scenes/slide/workskill01-houkokusou/slide/6.png"
  - "@scenes/slide/workskill01-houkokusou/slide/7.png"
  - "@scenes/slide/workskill01-houkokusou/slide/8.png"
  - "@scenes/slide/workskill01-houkokusou/slide/9.png"
  - "@scenes/slide/workskill01-houkokusou/slide/10.png"
  - "@scenes/slide/workskill01-houkokusou/slide/11.png"
  - "@scenes/slide/workskill01-houkokusou/slide/12.png"
  - "@scenes/slide/workskill01-houkokusou/slide/13.png"
  - "@scenes/slide/workskill01-houkokusou/slide/14.png"
  - "@scenes/slide/workskill01-houkokusou/slide/15.png"
  - "@scenes/slide/workskill01-houkokusou/slide/16.png"
  - "@scenes/slide/workskill01-houkokusou/slide/17.png"
  - "@scenes/slide/workskill01-houkokusou/slide/18.png"
  - "@scenes/slide/workskill01-houkokusou/slide/19.png"
  - "@scenes/slide/workskill01-houkokusou/slide/20.png"
  - "@scenes/slide/workskill01-houkokusou/slide/21.png"
  - "@scenes/slide/workskill01-houkokusou/slide/22.png"
  - "@scenes/slide/workskill01-houkokusou/slide/23.png"
  - "@scenes/slide/workskill01-houkokusou/slide/24.png"
  - "@scenes/slide/workskill01-houkokusou/slide/25.png"
  - "@scenes/slide/workskill01-houkokusou/slide/26.png"
  - "@scenes/slide/workskill01-houkokusou/slide/27.png"
  - "@scenes/slide/workskill01-houkokusou/slide/28.png"
  - "@scenes/slide/workskill01-houkokusou/slide/29.png"
  - "@scenes/slide/workskill01-houkokusou/slide/30.png"
  - "@scenes/slide/workskill01-houkokusou/slide/31.png"
  - "@scenes/slide/workskill01-houkokusou/slide/32.png"
  - "@scenes/slide/workskill01-houkokusou/slide/33.png"
  - "@scenes/slide/workskill01-houkokusou/slide/34.png"
  - "@scenes/slide/workskill01-houkokusou/slide/35.png"
  - "@scenes/slide/workskill01-houkokusou/slide/36.png"
  - "@scenes/slide/workskill01-houkokusou/slide/37.png"
  - "@scenes/slide/workskill01-houkokusou/slide/38.png"
  - "@scenes/slide/workskill01-houkokusou/slide/39.png"
  - "@scenes/slide/workskill01-houkokusou/slide/40.png"
  - "@scenes/slide/workskill01-houkokusou/slide/41.png"
  - "@scenes/slide/workskill01-houkokusou/slide/42.png"
  - "@scenes/slide/workskill01-houkokusou/slide/43.png"
  - "@scenes/slide/workskill01-houkokusou/slide/44.png"
