title: 保留・転送のマナー
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-phone-transfer/slide/1.png"
  - "@scenes/slide/call-phone-transfer/slide/2.png"
  - "@scenes/slide/call-phone-transfer/slide/3.png"
  - "@scenes/slide/call-phone-transfer/slide/4.png"
  - "@scenes/slide/call-phone-transfer/slide/5.png"
  - "@scenes/slide/call-phone-transfer/slide/6.png"
  - "@scenes/slide/call-phone-transfer/slide/7.png"
  - "@scenes/slide/call-phone-transfer/slide/8.png"
  - "@scenes/slide/call-phone-transfer/slide/9.png"
  - "@scenes/slide/call-phone-transfer/slide/10.png"
  - "@scenes/slide/call-phone-transfer/slide/11.png"
  - "@scenes/slide/call-phone-transfer/slide/12.png"
  - "@scenes/slide/call-phone-transfer/slide/13.png"
  - "@scenes/slide/call-phone-transfer/slide/14.png"
  - "@scenes/slide/call-phone-transfer/slide/15.png"
  - "@scenes/slide/call-phone-transfer/slide/16.png"
  - "@scenes/slide/call-phone-transfer/slide/17.png"
  - "@scenes/slide/call-phone-transfer/slide/18.png"
  - "@scenes/slide/call-phone-transfer/slide/19.png"
  - "@scenes/slide/call-phone-transfer/slide/20.png"
  - "@scenes/slide/call-phone-transfer/slide/21.png"
  - "@scenes/slide/call-phone-transfer/slide/22.png"
  - "@scenes/slide/call-phone-transfer/slide/23.png"
  - "@scenes/slide/call-phone-transfer/slide/24.png"
  - "@scenes/slide/call-phone-transfer/slide/25.png"
  - "@scenes/slide/call-phone-transfer/slide/26.png"
  - "@scenes/slide/call-phone-transfer/slide/27.png"
  - "@scenes/slide/call-phone-transfer/slide/28.png"
  - "@scenes/slide/call-phone-transfer/slide/29.png"
  - "@scenes/slide/call-phone-transfer/slide/30.png"
  - "@scenes/slide/call-phone-transfer/slide/31.png"
  - "@scenes/slide/call-phone-transfer/slide/32.png"
  - "@scenes/slide/call-phone-transfer/slide/33.png"
  - "@scenes/slide/call-phone-transfer/slide/34.png"
  - "@scenes/slide/call-phone-transfer/slide/35.png"
  - "@scenes/slide/call-phone-transfer/slide/36.png"
  - "@scenes/slide/call-phone-transfer/slide/37.png"
  - "@scenes/slide/call-phone-transfer/slide/38.png"
  - "@scenes/slide/call-phone-transfer/slide/39.png"
  - "@scenes/slide/call-phone-transfer/slide/40.png"
  - "@scenes/slide/call-phone-transfer/slide/41.png"
  - "@scenes/slide/call-phone-transfer/slide/42.png"
  - "@scenes/slide/call-phone-transfer/slide/43.png"
  - "@scenes/slide/call-phone-transfer/slide/44.png"
  - "@scenes/slide/call-phone-transfer/slide/45.png"
  - "@scenes/slide/call-phone-transfer/slide/46.png"
  - "@scenes/slide/call-phone-transfer/slide/47.png"
  - "@scenes/slide/call-phone-transfer/slide/48.png"
  - "@scenes/slide/call-phone-transfer/slide/49.png"
  - "@scenes/slide/call-phone-transfer/slide/50.png"
  - "@scenes/slide/call-phone-transfer/slide/51.png"
  - "@scenes/slide/call-phone-transfer/slide/52.png"
  - "@scenes/slide/call-phone-transfer/slide/53.png"
  - "@scenes/slide/call-phone-transfer/slide/54.png"
  - "@scenes/slide/call-phone-transfer/slide/55.png"
  - "@scenes/slide/call-phone-transfer/slide/56.png"
