title: よくわかる！ロジスティクス入門Ⅲ UNIT3
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/zh-logistics03-unit03/slide/1.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/2.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/3.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/4.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/5.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/6.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/7.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/8.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/9.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/10.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/11.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/12.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/13.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/14.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/15.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/16.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/17.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/18.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/19.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/20.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/21.png"
  - "@scenes/slide/zh-logistics03-unit03/slide/22.png"
