title: SOGIハラスメントの理解
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-sexual-sogi/slide/1.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/2.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/3.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/4.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/5.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/6.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/7.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/8.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/9.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/10.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/11.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/12.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/13.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/14.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/15.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/16.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/17.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/18.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/19.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/20.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/21.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/22.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/23.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/24.jpg"
  - "@scenes/slide/harass-sexual-sogi/slide/25.jpg"
