title: SOGIハラスメントの理解
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-sexual-sogi/slide/1.png"
  - "@scenes/slide/harass-sexual-sogi/slide/2.png"
  - "@scenes/slide/harass-sexual-sogi/slide/3.png"
  - "@scenes/slide/harass-sexual-sogi/slide/4.png"
  - "@scenes/slide/harass-sexual-sogi/slide/5.png"
  - "@scenes/slide/harass-sexual-sogi/slide/6.png"
  - "@scenes/slide/harass-sexual-sogi/slide/7.png"
  - "@scenes/slide/harass-sexual-sogi/slide/8.png"
  - "@scenes/slide/harass-sexual-sogi/slide/9.png"
  - "@scenes/slide/harass-sexual-sogi/slide/10.png"
  - "@scenes/slide/harass-sexual-sogi/slide/11.png"
  - "@scenes/slide/harass-sexual-sogi/slide/12.png"
  - "@scenes/slide/harass-sexual-sogi/slide/13.png"
  - "@scenes/slide/harass-sexual-sogi/slide/14.png"
  - "@scenes/slide/harass-sexual-sogi/slide/15.png"
  - "@scenes/slide/harass-sexual-sogi/slide/16.png"
  - "@scenes/slide/harass-sexual-sogi/slide/17.png"
  - "@scenes/slide/harass-sexual-sogi/slide/18.png"
  - "@scenes/slide/harass-sexual-sogi/slide/19.png"
  - "@scenes/slide/harass-sexual-sogi/slide/20.png"
  - "@scenes/slide/harass-sexual-sogi/slide/21.png"
  - "@scenes/slide/harass-sexual-sogi/slide/22.png"
  - "@scenes/slide/harass-sexual-sogi/slide/23.png"
  - "@scenes/slide/harass-sexual-sogi/slide/24.png"
  - "@scenes/slide/harass-sexual-sogi/slide/25.png"
  - "@scenes/slide/harass-sexual-sogi/slide/26.png"
  - "@scenes/slide/harass-sexual-sogi/slide/27.png"
  - "@scenes/slide/harass-sexual-sogi/slide/28.png"
  - "@scenes/slide/harass-sexual-sogi/slide/29.png"
  - "@scenes/slide/harass-sexual-sogi/slide/30.png"
  - "@scenes/slide/harass-sexual-sogi/slide/31.png"
  - "@scenes/slide/harass-sexual-sogi/slide/32.png"
  - "@scenes/slide/harass-sexual-sogi/slide/33.png"
  - "@scenes/slide/harass-sexual-sogi/slide/34.png"
  - "@scenes/slide/harass-sexual-sogi/slide/35.png"
  - "@scenes/slide/harass-sexual-sogi/slide/36.png"
  - "@scenes/slide/harass-sexual-sogi/slide/37.png"
  - "@scenes/slide/harass-sexual-sogi/slide/38.png"
  - "@scenes/slide/harass-sexual-sogi/slide/39.png"
  - "@scenes/slide/harass-sexual-sogi/slide/40.png"
  - "@scenes/slide/harass-sexual-sogi/slide/41.png"
  - "@scenes/slide/harass-sexual-sogi/slide/42.png"
  - "@scenes/slide/harass-sexual-sogi/slide/43.png"
  - "@scenes/slide/harass-sexual-sogi/slide/44.png"
  - "@scenes/slide/harass-sexual-sogi/slide/45.png"
  - "@scenes/slide/harass-sexual-sogi/slide/46.png"
  - "@scenes/slide/harass-sexual-sogi/slide/47.png"
  - "@scenes/slide/harass-sexual-sogi/slide/48.png"
  - "@scenes/slide/harass-sexual-sogi/slide/49.png"
