title: 安全管理措置と漏洩対応
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/privacy-safety/slide/1.png"
  - "@scenes/slide/privacy-safety/slide/2.png"
  - "@scenes/slide/privacy-safety/slide/3.png"
  - "@scenes/slide/privacy-safety/slide/4.png"
  - "@scenes/slide/privacy-safety/slide/5.png"
  - "@scenes/slide/privacy-safety/slide/6.png"
  - "@scenes/slide/privacy-safety/slide/7.png"
  - "@scenes/slide/privacy-safety/slide/8.png"
  - "@scenes/slide/privacy-safety/slide/9.png"
  - "@scenes/slide/privacy-safety/slide/10.png"
  - "@scenes/slide/privacy-safety/slide/11.png"
  - "@scenes/slide/privacy-safety/slide/12.png"
  - "@scenes/slide/privacy-safety/slide/13.png"
  - "@scenes/slide/privacy-safety/slide/14.png"
  - "@scenes/slide/privacy-safety/slide/15.png"
  - "@scenes/slide/privacy-safety/slide/16.png"
  - "@scenes/slide/privacy-safety/slide/17.png"
  - "@scenes/slide/privacy-safety/slide/18.png"
  - "@scenes/slide/privacy-safety/slide/19.png"
  - "@scenes/slide/privacy-safety/slide/20.png"
  - "@scenes/slide/privacy-safety/slide/21.png"
  - "@scenes/slide/privacy-safety/slide/22.png"
  - "@scenes/slide/privacy-safety/slide/23.png"
