title: 被害者・加害者にならないために
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-sexual-prevent/slide/1.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/2.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/3.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/4.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/5.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/6.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/7.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/8.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/9.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/10.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/11.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/12.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/13.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/14.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/15.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/16.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/17.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/18.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/19.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/20.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/21.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/22.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/23.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/24.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/25.jpg"
  - "@scenes/slide/harass-sexual-prevent/slide/26.jpg"
