title: 被害者・加害者にならないために
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-sexual-prevent/slide/1.png"
  - "@scenes/slide/harass-sexual-prevent/slide/2.png"
  - "@scenes/slide/harass-sexual-prevent/slide/3.png"
  - "@scenes/slide/harass-sexual-prevent/slide/4.png"
  - "@scenes/slide/harass-sexual-prevent/slide/5.png"
  - "@scenes/slide/harass-sexual-prevent/slide/6.png"
  - "@scenes/slide/harass-sexual-prevent/slide/7.png"
  - "@scenes/slide/harass-sexual-prevent/slide/8.png"
  - "@scenes/slide/harass-sexual-prevent/slide/9.png"
  - "@scenes/slide/harass-sexual-prevent/slide/10.png"
  - "@scenes/slide/harass-sexual-prevent/slide/11.png"
  - "@scenes/slide/harass-sexual-prevent/slide/12.png"
  - "@scenes/slide/harass-sexual-prevent/slide/13.png"
  - "@scenes/slide/harass-sexual-prevent/slide/14.png"
  - "@scenes/slide/harass-sexual-prevent/slide/15.png"
  - "@scenes/slide/harass-sexual-prevent/slide/16.png"
  - "@scenes/slide/harass-sexual-prevent/slide/17.png"
  - "@scenes/slide/harass-sexual-prevent/slide/18.png"
  - "@scenes/slide/harass-sexual-prevent/slide/19.png"
  - "@scenes/slide/harass-sexual-prevent/slide/20.png"
  - "@scenes/slide/harass-sexual-prevent/slide/21.png"
  - "@scenes/slide/harass-sexual-prevent/slide/22.png"
  - "@scenes/slide/harass-sexual-prevent/slide/23.png"
  - "@scenes/slide/harass-sexual-prevent/slide/24.png"
  - "@scenes/slide/harass-sexual-prevent/slide/25.png"
  - "@scenes/slide/harass-sexual-prevent/slide/26.png"
  - "@scenes/slide/harass-sexual-prevent/slide/27.png"
  - "@scenes/slide/harass-sexual-prevent/slide/28.png"
  - "@scenes/slide/harass-sexual-prevent/slide/29.png"
  - "@scenes/slide/harass-sexual-prevent/slide/30.png"
  - "@scenes/slide/harass-sexual-prevent/slide/31.png"
  - "@scenes/slide/harass-sexual-prevent/slide/32.png"
  - "@scenes/slide/harass-sexual-prevent/slide/33.png"
  - "@scenes/slide/harass-sexual-prevent/slide/34.png"
  - "@scenes/slide/harass-sexual-prevent/slide/35.png"
  - "@scenes/slide/harass-sexual-prevent/slide/36.png"
  - "@scenes/slide/harass-sexual-prevent/slide/37.png"
  - "@scenes/slide/harass-sexual-prevent/slide/38.png"
  - "@scenes/slide/harass-sexual-prevent/slide/39.png"
  - "@scenes/slide/harass-sexual-prevent/slide/40.png"
  - "@scenes/slide/harass-sexual-prevent/slide/41.png"
  - "@scenes/slide/harass-sexual-prevent/slide/42.png"
  - "@scenes/slide/harass-sexual-prevent/slide/43.png"
  - "@scenes/slide/harass-sexual-prevent/slide/44.png"
  - "@scenes/slide/harass-sexual-prevent/slide/45.png"
  - "@scenes/slide/harass-sexual-prevent/slide/46.png"
  - "@scenes/slide/harass-sexual-prevent/slide/47.png"
  - "@scenes/slide/harass-sexual-prevent/slide/48.png"
  - "@scenes/slide/harass-sexual-prevent/slide/49.png"
  - "@scenes/slide/harass-sexual-prevent/slide/50.png"
  - "@scenes/slide/harass-sexual-prevent/slide/51.png"
