title: 社内文書・社外文書の違い
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/biz-doc-internal-external/slide/1.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/2.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/3.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/4.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/5.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/6.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/7.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/8.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/9.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/10.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/11.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/12.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/13.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/14.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/15.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/16.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/17.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/18.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/19.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/20.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/21.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/22.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/23.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/24.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/25.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/26.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/27.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/28.jpg"
  - "@scenes/slide/biz-doc-internal-external/slide/29.jpg"
