title: 社内文書・社外文書の違い
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/biz-doc-internal-external/slide/1.png"
  - "@scenes/slide/biz-doc-internal-external/slide/2.png"
  - "@scenes/slide/biz-doc-internal-external/slide/3.png"
  - "@scenes/slide/biz-doc-internal-external/slide/4.png"
  - "@scenes/slide/biz-doc-internal-external/slide/5.png"
  - "@scenes/slide/biz-doc-internal-external/slide/6.png"
  - "@scenes/slide/biz-doc-internal-external/slide/7.png"
  - "@scenes/slide/biz-doc-internal-external/slide/8.png"
  - "@scenes/slide/biz-doc-internal-external/slide/9.png"
  - "@scenes/slide/biz-doc-internal-external/slide/10.png"
  - "@scenes/slide/biz-doc-internal-external/slide/11.png"
  - "@scenes/slide/biz-doc-internal-external/slide/12.png"
  - "@scenes/slide/biz-doc-internal-external/slide/13.png"
  - "@scenes/slide/biz-doc-internal-external/slide/14.png"
  - "@scenes/slide/biz-doc-internal-external/slide/15.png"
  - "@scenes/slide/biz-doc-internal-external/slide/16.png"
  - "@scenes/slide/biz-doc-internal-external/slide/17.png"
  - "@scenes/slide/biz-doc-internal-external/slide/18.png"
  - "@scenes/slide/biz-doc-internal-external/slide/19.png"
  - "@scenes/slide/biz-doc-internal-external/slide/20.png"
  - "@scenes/slide/biz-doc-internal-external/slide/21.png"
  - "@scenes/slide/biz-doc-internal-external/slide/22.png"
  - "@scenes/slide/biz-doc-internal-external/slide/23.png"
  - "@scenes/slide/biz-doc-internal-external/slide/24.png"
  - "@scenes/slide/biz-doc-internal-external/slide/25.png"
  - "@scenes/slide/biz-doc-internal-external/slide/26.png"
  - "@scenes/slide/biz-doc-internal-external/slide/27.png"
  - "@scenes/slide/biz-doc-internal-external/slide/28.png"
  - "@scenes/slide/biz-doc-internal-external/slide/29.png"
  - "@scenes/slide/biz-doc-internal-external/slide/30.png"
  - "@scenes/slide/biz-doc-internal-external/slide/31.png"
  - "@scenes/slide/biz-doc-internal-external/slide/32.png"
  - "@scenes/slide/biz-doc-internal-external/slide/33.png"
  - "@scenes/slide/biz-doc-internal-external/slide/34.png"
  - "@scenes/slide/biz-doc-internal-external/slide/35.png"
  - "@scenes/slide/biz-doc-internal-external/slide/36.png"
  - "@scenes/slide/biz-doc-internal-external/slide/37.png"
  - "@scenes/slide/biz-doc-internal-external/slide/38.png"
  - "@scenes/slide/biz-doc-internal-external/slide/39.png"
  - "@scenes/slide/biz-doc-internal-external/slide/40.png"
  - "@scenes/slide/biz-doc-internal-external/slide/41.png"
  - "@scenes/slide/biz-doc-internal-external/slide/42.png"
  - "@scenes/slide/biz-doc-internal-external/slide/43.png"
  - "@scenes/slide/biz-doc-internal-external/slide/44.png"
  - "@scenes/slide/biz-doc-internal-external/slide/45.png"
  - "@scenes/slide/biz-doc-internal-external/slide/46.png"
  - "@scenes/slide/biz-doc-internal-external/slide/47.png"
  - "@scenes/slide/biz-doc-internal-external/slide/48.png"
  - "@scenes/slide/biz-doc-internal-external/slide/49.png"
  - "@scenes/slide/biz-doc-internal-external/slide/50.png"
  - "@scenes/slide/biz-doc-internal-external/slide/51.png"
  - "@scenes/slide/biz-doc-internal-external/slide/52.png"
  - "@scenes/slide/biz-doc-internal-external/slide/53.png"
  - "@scenes/slide/biz-doc-internal-external/slide/54.png"
  - "@scenes/slide/biz-doc-internal-external/slide/55.png"
  - "@scenes/slide/biz-doc-internal-external/slide/56.png"
  - "@scenes/slide/biz-doc-internal-external/slide/57.png"
