title: 轻松理解！物流入门Ⅱ UNIT2
btn_next_scene_name: 下一个
slide_speed: 10
img:
  - "@scenes/slide/zh-logistics02-unit02/slide/1.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/2.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/3.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/4.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/5.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/6.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/7.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/8.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/9.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/10.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/11.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/12.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/13.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/14.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/15.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/16.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/17.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/18.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/19.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/20.jpg"
  - "@scenes/slide/zh-logistics02-unit02/slide/21.jpg"
