title: 職場での具体的事例と判断基準
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-sexual-cases/slide/1.png"
  - "@scenes/slide/harass-sexual-cases/slide/2.png"
  - "@scenes/slide/harass-sexual-cases/slide/3.png"
  - "@scenes/slide/harass-sexual-cases/slide/4.png"
  - "@scenes/slide/harass-sexual-cases/slide/5.png"
  - "@scenes/slide/harass-sexual-cases/slide/6.png"
  - "@scenes/slide/harass-sexual-cases/slide/7.png"
  - "@scenes/slide/harass-sexual-cases/slide/8.png"
  - "@scenes/slide/harass-sexual-cases/slide/9.png"
  - "@scenes/slide/harass-sexual-cases/slide/10.png"
  - "@scenes/slide/harass-sexual-cases/slide/11.png"
  - "@scenes/slide/harass-sexual-cases/slide/12.png"
  - "@scenes/slide/harass-sexual-cases/slide/13.png"
  - "@scenes/slide/harass-sexual-cases/slide/14.png"
  - "@scenes/slide/harass-sexual-cases/slide/15.png"
  - "@scenes/slide/harass-sexual-cases/slide/16.png"
  - "@scenes/slide/harass-sexual-cases/slide/17.png"
  - "@scenes/slide/harass-sexual-cases/slide/18.png"
  - "@scenes/slide/harass-sexual-cases/slide/19.png"
  - "@scenes/slide/harass-sexual-cases/slide/20.png"
  - "@scenes/slide/harass-sexual-cases/slide/21.png"
  - "@scenes/slide/harass-sexual-cases/slide/22.png"
  - "@scenes/slide/harass-sexual-cases/slide/23.png"
  - "@scenes/slide/harass-sexual-cases/slide/24.png"
  - "@scenes/slide/harass-sexual-cases/slide/25.png"
  - "@scenes/slide/harass-sexual-cases/slide/26.png"
  - "@scenes/slide/harass-sexual-cases/slide/27.png"
  - "@scenes/slide/harass-sexual-cases/slide/28.png"
  - "@scenes/slide/harass-sexual-cases/slide/29.png"
  - "@scenes/slide/harass-sexual-cases/slide/30.png"
  - "@scenes/slide/harass-sexual-cases/slide/31.png"
  - "@scenes/slide/harass-sexual-cases/slide/32.png"
  - "@scenes/slide/harass-sexual-cases/slide/33.png"
  - "@scenes/slide/harass-sexual-cases/slide/34.png"
  - "@scenes/slide/harass-sexual-cases/slide/35.png"
  - "@scenes/slide/harass-sexual-cases/slide/36.png"
  - "@scenes/slide/harass-sexual-cases/slide/37.png"
  - "@scenes/slide/harass-sexual-cases/slide/38.png"
  - "@scenes/slide/harass-sexual-cases/slide/39.png"
  - "@scenes/slide/harass-sexual-cases/slide/40.png"
  - "@scenes/slide/harass-sexual-cases/slide/41.png"
  - "@scenes/slide/harass-sexual-cases/slide/42.png"
  - "@scenes/slide/harass-sexual-cases/slide/43.png"
  - "@scenes/slide/harass-sexual-cases/slide/44.png"
  - "@scenes/slide/harass-sexual-cases/slide/45.png"
  - "@scenes/slide/harass-sexual-cases/slide/46.png"
  - "@scenes/slide/harass-sexual-cases/slide/47.png"
  - "@scenes/slide/harass-sexual-cases/slide/48.png"
  - "@scenes/slide/harass-sexual-cases/slide/49.png"
