title: 職場での具体的事例と判断基準
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-sexual-cases/slide/1.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/2.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/3.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/4.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/5.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/6.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/7.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/8.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/9.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/10.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/11.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/12.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/13.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/14.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/15.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/16.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/17.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/18.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/19.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/20.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/21.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/22.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/23.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/24.jpg"
  - "@scenes/slide/harass-sexual-cases/slide/25.jpg"
