title: Dễ hiểu! Nhập môn Logistics Ⅳ UNIT1
btn_next_scene_name: Tiếp theo
slide_speed: 10
img:
  - "@scenes/slide/vi-logistics04-unit01/slide/1.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/2.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/3.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/4.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/5.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/6.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/7.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/8.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/9.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/10.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/11.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/12.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/13.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/14.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/15.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/16.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/17.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/18.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/19.jpg"
  - "@scenes/slide/vi-logistics04-unit01/slide/20.jpg"
