title: 仕事の段取りと優先順位の付け方
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-priority/slide/1.png"
  - "@scenes/slide/workskill01-priority/slide/2.png"
  - "@scenes/slide/workskill01-priority/slide/3.png"
  - "@scenes/slide/workskill01-priority/slide/4.png"
  - "@scenes/slide/workskill01-priority/slide/5.png"
  - "@scenes/slide/workskill01-priority/slide/6.png"
  - "@scenes/slide/workskill01-priority/slide/7.png"
  - "@scenes/slide/workskill01-priority/slide/8.png"
  - "@scenes/slide/workskill01-priority/slide/9.png"
  - "@scenes/slide/workskill01-priority/slide/10.png"
  - "@scenes/slide/workskill01-priority/slide/11.png"
  - "@scenes/slide/workskill01-priority/slide/12.png"
  - "@scenes/slide/workskill01-priority/slide/13.png"
  - "@scenes/slide/workskill01-priority/slide/14.png"
  - "@scenes/slide/workskill01-priority/slide/15.png"
  - "@scenes/slide/workskill01-priority/slide/16.png"
  - "@scenes/slide/workskill01-priority/slide/17.png"
  - "@scenes/slide/workskill01-priority/slide/18.png"
  - "@scenes/slide/workskill01-priority/slide/19.png"
  - "@scenes/slide/workskill01-priority/slide/20.png"
  - "@scenes/slide/workskill01-priority/slide/21.png"
  - "@scenes/slide/workskill01-priority/slide/22.png"
