title: 仕事の段取りと優先順位の付け方
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-priority/slide/1.jpg"
  - "@scenes/slide/workskill01-priority/slide/2.jpg"
  - "@scenes/slide/workskill01-priority/slide/3.jpg"
  - "@scenes/slide/workskill01-priority/slide/4.jpg"
  - "@scenes/slide/workskill01-priority/slide/5.jpg"
  - "@scenes/slide/workskill01-priority/slide/6.jpg"
  - "@scenes/slide/workskill01-priority/slide/7.jpg"
  - "@scenes/slide/workskill01-priority/slide/8.jpg"
  - "@scenes/slide/workskill01-priority/slide/9.jpg"
  - "@scenes/slide/workskill01-priority/slide/10.jpg"
  - "@scenes/slide/workskill01-priority/slide/11.jpg"
  - "@scenes/slide/workskill01-priority/slide/12.jpg"
  - "@scenes/slide/workskill01-priority/slide/13.jpg"
  - "@scenes/slide/workskill01-priority/slide/14.jpg"
  - "@scenes/slide/workskill01-priority/slide/15.jpg"
  - "@scenes/slide/workskill01-priority/slide/16.jpg"
  - "@scenes/slide/workskill01-priority/slide/17.jpg"
  - "@scenes/slide/workskill01-priority/slide/18.jpg"
  - "@scenes/slide/workskill01-priority/slide/19.jpg"
  - "@scenes/slide/workskill01-priority/slide/20.jpg"
  - "@scenes/slide/workskill01-priority/slide/21.jpg"
  - "@scenes/slide/workskill01-priority/slide/22.jpg"
