title: 第一印象を決める発声・滑舌
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-phone-voice/slide/1.png"
  - "@scenes/slide/call-phone-voice/slide/2.png"
  - "@scenes/slide/call-phone-voice/slide/3.png"
  - "@scenes/slide/call-phone-voice/slide/4.png"
  - "@scenes/slide/call-phone-voice/slide/5.png"
  - "@scenes/slide/call-phone-voice/slide/6.png"
  - "@scenes/slide/call-phone-voice/slide/7.png"
  - "@scenes/slide/call-phone-voice/slide/8.png"
  - "@scenes/slide/call-phone-voice/slide/9.png"
  - "@scenes/slide/call-phone-voice/slide/10.png"
  - "@scenes/slide/call-phone-voice/slide/11.png"
  - "@scenes/slide/call-phone-voice/slide/12.png"
  - "@scenes/slide/call-phone-voice/slide/13.png"
  - "@scenes/slide/call-phone-voice/slide/14.png"
  - "@scenes/slide/call-phone-voice/slide/15.png"
  - "@scenes/slide/call-phone-voice/slide/16.png"
  - "@scenes/slide/call-phone-voice/slide/17.png"
  - "@scenes/slide/call-phone-voice/slide/18.png"
  - "@scenes/slide/call-phone-voice/slide/19.png"
  - "@scenes/slide/call-phone-voice/slide/20.png"
  - "@scenes/slide/call-phone-voice/slide/21.png"
  - "@scenes/slide/call-phone-voice/slide/22.png"
  - "@scenes/slide/call-phone-voice/slide/23.png"
  - "@scenes/slide/call-phone-voice/slide/24.png"
  - "@scenes/slide/call-phone-voice/slide/25.png"
  - "@scenes/slide/call-phone-voice/slide/26.png"
  - "@scenes/slide/call-phone-voice/slide/27.png"
  - "@scenes/slide/call-phone-voice/slide/28.png"
  - "@scenes/slide/call-phone-voice/slide/29.png"
  - "@scenes/slide/call-phone-voice/slide/30.png"
  - "@scenes/slide/call-phone-voice/slide/31.png"
  - "@scenes/slide/call-phone-voice/slide/32.png"
  - "@scenes/slide/call-phone-voice/slide/33.png"
  - "@scenes/slide/call-phone-voice/slide/34.png"
  - "@scenes/slide/call-phone-voice/slide/35.png"
  - "@scenes/slide/call-phone-voice/slide/36.png"
  - "@scenes/slide/call-phone-voice/slide/37.png"
  - "@scenes/slide/call-phone-voice/slide/38.png"
  - "@scenes/slide/call-phone-voice/slide/39.png"
  - "@scenes/slide/call-phone-voice/slide/40.png"
  - "@scenes/slide/call-phone-voice/slide/41.png"
  - "@scenes/slide/call-phone-voice/slide/42.png"
  - "@scenes/slide/call-phone-voice/slide/43.png"
  - "@scenes/slide/call-phone-voice/slide/44.png"
  - "@scenes/slide/call-phone-voice/slide/45.png"
  - "@scenes/slide/call-phone-voice/slide/46.png"
  - "@scenes/slide/call-phone-voice/slide/47.png"
  - "@scenes/slide/call-phone-voice/slide/48.png"
  - "@scenes/slide/call-phone-voice/slide/49.png"
  - "@scenes/slide/call-phone-voice/slide/50.png"
  - "@scenes/slide/call-phone-voice/slide/51.png"
  - "@scenes/slide/call-phone-voice/slide/52.png"
  - "@scenes/slide/call-phone-voice/slide/53.png"
  - "@scenes/slide/call-phone-voice/slide/54.png"
  - "@scenes/slide/call-phone-voice/slide/55.png"
