title: 第一印象を決める発声・滑舌
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-phone-voice/slide/1.jpg"
  - "@scenes/slide/call-phone-voice/slide/2.jpg"
  - "@scenes/slide/call-phone-voice/slide/3.jpg"
  - "@scenes/slide/call-phone-voice/slide/4.jpg"
  - "@scenes/slide/call-phone-voice/slide/5.jpg"
  - "@scenes/slide/call-phone-voice/slide/6.jpg"
  - "@scenes/slide/call-phone-voice/slide/7.jpg"
  - "@scenes/slide/call-phone-voice/slide/8.jpg"
  - "@scenes/slide/call-phone-voice/slide/9.jpg"
  - "@scenes/slide/call-phone-voice/slide/10.jpg"
  - "@scenes/slide/call-phone-voice/slide/11.jpg"
  - "@scenes/slide/call-phone-voice/slide/12.jpg"
  - "@scenes/slide/call-phone-voice/slide/13.jpg"
  - "@scenes/slide/call-phone-voice/slide/14.jpg"
  - "@scenes/slide/call-phone-voice/slide/15.jpg"
  - "@scenes/slide/call-phone-voice/slide/16.jpg"
  - "@scenes/slide/call-phone-voice/slide/17.jpg"
  - "@scenes/slide/call-phone-voice/slide/18.jpg"
  - "@scenes/slide/call-phone-voice/slide/19.jpg"
  - "@scenes/slide/call-phone-voice/slide/20.jpg"
  - "@scenes/slide/call-phone-voice/slide/21.jpg"
  - "@scenes/slide/call-phone-voice/slide/22.jpg"
  - "@scenes/slide/call-phone-voice/slide/23.jpg"
  - "@scenes/slide/call-phone-voice/slide/24.jpg"
  - "@scenes/slide/call-phone-voice/slide/25.jpg"
  - "@scenes/slide/call-phone-voice/slide/26.jpg"
  - "@scenes/slide/call-phone-voice/slide/27.jpg"
  - "@scenes/slide/call-phone-voice/slide/28.jpg"
  - "@scenes/slide/call-phone-voice/slide/29.jpg"
  - "@scenes/slide/call-phone-voice/slide/30.jpg"
  - "@scenes/slide/call-phone-voice/slide/31.jpg"
  - "@scenes/slide/call-phone-voice/slide/32.jpg"
  - "@scenes/slide/call-phone-voice/slide/33.jpg"
  - "@scenes/slide/call-phone-voice/slide/34.jpg"
  - "@scenes/slide/call-phone-voice/slide/35.jpg"
  - "@scenes/slide/call-phone-voice/slide/36.jpg"
  - "@scenes/slide/call-phone-voice/slide/37.jpg"
  - "@scenes/slide/call-phone-voice/slide/38.jpg"
  - "@scenes/slide/call-phone-voice/slide/39.jpg"
  - "@scenes/slide/call-phone-voice/slide/40.jpg"
  - "@scenes/slide/call-phone-voice/slide/41.jpg"
  - "@scenes/slide/call-phone-voice/slide/42.jpg"
  - "@scenes/slide/call-phone-voice/slide/43.jpg"
  - "@scenes/slide/call-phone-voice/slide/44.jpg"
  - "@scenes/slide/call-phone-voice/slide/45.jpg"
  - "@scenes/slide/call-phone-voice/slide/46.jpg"
  - "@scenes/slide/call-phone-voice/slide/47.jpg"
  - "@scenes/slide/call-phone-voice/slide/48.jpg"
  - "@scenes/slide/call-phone-voice/slide/49.jpg"
  - "@scenes/slide/call-phone-voice/slide/50.jpg"
  - "@scenes/slide/call-phone-voice/slide/51.jpg"
  - "@scenes/slide/call-phone-voice/slide/52.jpg"
  - "@scenes/slide/call-phone-voice/slide/53.jpg"
  - "@scenes/slide/call-phone-voice/slide/54.jpg"
  - "@scenes/slide/call-phone-voice/slide/55.jpg"
