title: 「聴く力」と「伝える力」の基本
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-listening-speaking/slide/1.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/2.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/3.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/4.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/5.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/6.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/7.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/8.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/9.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/10.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/11.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/12.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/13.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/14.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/15.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/16.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/17.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/18.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/19.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/20.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/21.jpg"
  - "@scenes/slide/workskill01-listening-speaking/slide/22.jpg"
