title: 「聴く力」と「伝える力」の基本
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill01-listening-speaking/slide/1.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/2.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/3.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/4.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/5.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/6.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/7.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/8.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/9.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/10.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/11.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/12.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/13.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/14.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/15.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/16.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/17.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/18.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/19.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/20.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/21.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/22.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/23.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/24.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/25.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/26.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/27.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/28.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/29.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/30.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/31.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/32.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/33.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/34.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/35.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/36.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/37.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/38.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/39.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/40.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/41.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/42.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/43.png"
  - "@scenes/slide/workskill01-listening-speaking/slide/44.png"
