title: 事実と意見の明確な区別
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/report-minutes-fact-opinion/slide/1.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/2.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/3.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/4.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/5.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/6.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/7.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/8.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/9.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/10.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/11.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/12.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/13.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/14.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/15.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/16.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/17.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/18.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/19.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/20.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/21.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/22.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/23.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/24.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/25.jpg"
  - "@scenes/slide/report-minutes-fact-opinion/slide/26.jpg"
