title: 事実と意見の明確な区別
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/report-minutes-fact-opinion/slide/1.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/2.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/3.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/4.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/5.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/6.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/7.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/8.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/9.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/10.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/11.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/12.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/13.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/14.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/15.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/16.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/17.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/18.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/19.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/20.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/21.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/22.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/23.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/24.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/25.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/26.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/27.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/28.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/29.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/30.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/31.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/32.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/33.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/34.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/35.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/36.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/37.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/38.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/39.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/40.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/41.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/42.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/43.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/44.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/45.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/46.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/47.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/48.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/49.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/50.png"
  - "@scenes/slide/report-minutes-fact-opinion/slide/51.png"
