title: 個人情報の取得・利用・提供のルール
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/privacy-rules/slide/1.png"
  - "@scenes/slide/privacy-rules/slide/2.png"
  - "@scenes/slide/privacy-rules/slide/3.png"
  - "@scenes/slide/privacy-rules/slide/4.png"
  - "@scenes/slide/privacy-rules/slide/5.png"
  - "@scenes/slide/privacy-rules/slide/6.png"
  - "@scenes/slide/privacy-rules/slide/7.png"
  - "@scenes/slide/privacy-rules/slide/8.png"
  - "@scenes/slide/privacy-rules/slide/9.png"
  - "@scenes/slide/privacy-rules/slide/10.png"
  - "@scenes/slide/privacy-rules/slide/11.png"
  - "@scenes/slide/privacy-rules/slide/12.png"
  - "@scenes/slide/privacy-rules/slide/13.png"
  - "@scenes/slide/privacy-rules/slide/14.png"
  - "@scenes/slide/privacy-rules/slide/15.png"
  - "@scenes/slide/privacy-rules/slide/16.png"
  - "@scenes/slide/privacy-rules/slide/17.png"
  - "@scenes/slide/privacy-rules/slide/18.png"
  - "@scenes/slide/privacy-rules/slide/19.png"
  - "@scenes/slide/privacy-rules/slide/20.png"
  - "@scenes/slide/privacy-rules/slide/21.png"
  - "@scenes/slide/privacy-rules/slide/22.png"
