title: Rules for Obtaining, Using, and Providing Personal Information
btn_next_scene_name: Next
slide_speed: 10
img:
  - "@scenes/slide/privacy-rules/slide/1.jpg"
  - "@scenes/slide/privacy-rules/slide/2.jpg"
  - "@scenes/slide/privacy-rules/slide/3.jpg"
  - "@scenes/slide/privacy-rules/slide/4.jpg"
  - "@scenes/slide/privacy-rules/slide/5.jpg"
  - "@scenes/slide/privacy-rules/slide/6.jpg"
  - "@scenes/slide/privacy-rules/slide/7.jpg"
  - "@scenes/slide/privacy-rules/slide/8.jpg"
  - "@scenes/slide/privacy-rules/slide/9.jpg"
  - "@scenes/slide/privacy-rules/slide/10.jpg"
  - "@scenes/slide/privacy-rules/slide/11.jpg"
  - "@scenes/slide/privacy-rules/slide/12.jpg"
  - "@scenes/slide/privacy-rules/slide/13.jpg"
  - "@scenes/slide/privacy-rules/slide/14.jpg"
  - "@scenes/slide/privacy-rules/slide/15.jpg"
  - "@scenes/slide/privacy-rules/slide/16.jpg"
  - "@scenes/slide/privacy-rules/slide/17.jpg"
  - "@scenes/slide/privacy-rules/slide/18.jpg"
  - "@scenes/slide/privacy-rules/slide/19.jpg"
  - "@scenes/slide/privacy-rules/slide/20.jpg"
  - "@scenes/slide/privacy-rules/slide/21.jpg"
  - "@scenes/slide/privacy-rules/slide/22.jpg"
