title: クレームの種類と顧客心理
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-claim-types/slide/1.jpg"
  - "@scenes/slide/call-claim-types/slide/2.jpg"
  - "@scenes/slide/call-claim-types/slide/3.jpg"
  - "@scenes/slide/call-claim-types/slide/4.jpg"
  - "@scenes/slide/call-claim-types/slide/5.jpg"
  - "@scenes/slide/call-claim-types/slide/6.jpg"
  - "@scenes/slide/call-claim-types/slide/7.jpg"
  - "@scenes/slide/call-claim-types/slide/8.jpg"
  - "@scenes/slide/call-claim-types/slide/9.jpg"
  - "@scenes/slide/call-claim-types/slide/10.jpg"
  - "@scenes/slide/call-claim-types/slide/11.jpg"
  - "@scenes/slide/call-claim-types/slide/12.jpg"
  - "@scenes/slide/call-claim-types/slide/13.jpg"
  - "@scenes/slide/call-claim-types/slide/14.jpg"
  - "@scenes/slide/call-claim-types/slide/15.jpg"
  - "@scenes/slide/call-claim-types/slide/16.jpg"
  - "@scenes/slide/call-claim-types/slide/17.jpg"
  - "@scenes/slide/call-claim-types/slide/18.jpg"
  - "@scenes/slide/call-claim-types/slide/19.jpg"
  - "@scenes/slide/call-claim-types/slide/20.jpg"
  - "@scenes/slide/call-claim-types/slide/21.jpg"
  - "@scenes/slide/call-claim-types/slide/22.jpg"
  - "@scenes/slide/call-claim-types/slide/23.jpg"
  - "@scenes/slide/call-claim-types/slide/24.jpg"
  - "@scenes/slide/call-claim-types/slide/25.jpg"
  - "@scenes/slide/call-claim-types/slide/26.jpg"
  - "@scenes/slide/call-claim-types/slide/27.jpg"
  - "@scenes/slide/call-claim-types/slide/28.jpg"
  - "@scenes/slide/call-claim-types/slide/29.jpg"
  - "@scenes/slide/call-claim-types/slide/30.jpg"
  - "@scenes/slide/call-claim-types/slide/31.jpg"
  - "@scenes/slide/call-claim-types/slide/32.jpg"
  - "@scenes/slide/call-claim-types/slide/33.jpg"
  - "@scenes/slide/call-claim-types/slide/34.jpg"
  - "@scenes/slide/call-claim-types/slide/35.jpg"
  - "@scenes/slide/call-claim-types/slide/36.jpg"
  - "@scenes/slide/call-claim-types/slide/37.jpg"
  - "@scenes/slide/call-claim-types/slide/38.jpg"
  - "@scenes/slide/call-claim-types/slide/39.jpg"
  - "@scenes/slide/call-claim-types/slide/40.jpg"
  - "@scenes/slide/call-claim-types/slide/41.jpg"
  - "@scenes/slide/call-claim-types/slide/42.jpg"
  - "@scenes/slide/call-claim-types/slide/43.jpg"
  - "@scenes/slide/call-claim-types/slide/44.jpg"
  - "@scenes/slide/call-claim-types/slide/45.jpg"
  - "@scenes/slide/call-claim-types/slide/46.jpg"
  - "@scenes/slide/call-claim-types/slide/47.jpg"
  - "@scenes/slide/call-claim-types/slide/48.jpg"
  - "@scenes/slide/call-claim-types/slide/49.jpg"
  - "@scenes/slide/call-claim-types/slide/50.jpg"
  - "@scenes/slide/call-claim-types/slide/51.jpg"
