title: クレームの種類と顧客心理
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-claim-types/slide/1.png"
  - "@scenes/slide/call-claim-types/slide/2.png"
  - "@scenes/slide/call-claim-types/slide/3.png"
  - "@scenes/slide/call-claim-types/slide/4.png"
  - "@scenes/slide/call-claim-types/slide/5.png"
  - "@scenes/slide/call-claim-types/slide/6.png"
  - "@scenes/slide/call-claim-types/slide/7.png"
  - "@scenes/slide/call-claim-types/slide/8.png"
  - "@scenes/slide/call-claim-types/slide/9.png"
  - "@scenes/slide/call-claim-types/slide/10.png"
  - "@scenes/slide/call-claim-types/slide/11.png"
  - "@scenes/slide/call-claim-types/slide/12.png"
  - "@scenes/slide/call-claim-types/slide/13.png"
  - "@scenes/slide/call-claim-types/slide/14.png"
  - "@scenes/slide/call-claim-types/slide/15.png"
  - "@scenes/slide/call-claim-types/slide/16.png"
  - "@scenes/slide/call-claim-types/slide/17.png"
  - "@scenes/slide/call-claim-types/slide/18.png"
  - "@scenes/slide/call-claim-types/slide/19.png"
  - "@scenes/slide/call-claim-types/slide/20.png"
  - "@scenes/slide/call-claim-types/slide/21.png"
  - "@scenes/slide/call-claim-types/slide/22.png"
  - "@scenes/slide/call-claim-types/slide/23.png"
  - "@scenes/slide/call-claim-types/slide/24.png"
  - "@scenes/slide/call-claim-types/slide/25.png"
  - "@scenes/slide/call-claim-types/slide/26.png"
  - "@scenes/slide/call-claim-types/slide/27.png"
  - "@scenes/slide/call-claim-types/slide/28.png"
  - "@scenes/slide/call-claim-types/slide/29.png"
  - "@scenes/slide/call-claim-types/slide/30.png"
  - "@scenes/slide/call-claim-types/slide/31.png"
  - "@scenes/slide/call-claim-types/slide/32.png"
  - "@scenes/slide/call-claim-types/slide/33.png"
  - "@scenes/slide/call-claim-types/slide/34.png"
  - "@scenes/slide/call-claim-types/slide/35.png"
  - "@scenes/slide/call-claim-types/slide/36.png"
  - "@scenes/slide/call-claim-types/slide/37.png"
  - "@scenes/slide/call-claim-types/slide/38.png"
  - "@scenes/slide/call-claim-types/slide/39.png"
  - "@scenes/slide/call-claim-types/slide/40.png"
  - "@scenes/slide/call-claim-types/slide/41.png"
  - "@scenes/slide/call-claim-types/slide/42.png"
  - "@scenes/slide/call-claim-types/slide/43.png"
  - "@scenes/slide/call-claim-types/slide/44.png"
  - "@scenes/slide/call-claim-types/slide/45.png"
  - "@scenes/slide/call-claim-types/slide/46.png"
  - "@scenes/slide/call-claim-types/slide/47.png"
  - "@scenes/slide/call-claim-types/slide/48.png"
  - "@scenes/slide/call-claim-types/slide/49.png"
  - "@scenes/slide/call-claim-types/slide/50.png"
  - "@scenes/slide/call-claim-types/slide/51.png"
