title: 敬語と言葉遣い（クッション言葉）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-phone-keigo/slide/1.jpg"
  - "@scenes/slide/call-phone-keigo/slide/2.jpg"
  - "@scenes/slide/call-phone-keigo/slide/3.jpg"
  - "@scenes/slide/call-phone-keigo/slide/4.jpg"
  - "@scenes/slide/call-phone-keigo/slide/5.jpg"
  - "@scenes/slide/call-phone-keigo/slide/6.jpg"
  - "@scenes/slide/call-phone-keigo/slide/7.jpg"
  - "@scenes/slide/call-phone-keigo/slide/8.jpg"
  - "@scenes/slide/call-phone-keigo/slide/9.jpg"
  - "@scenes/slide/call-phone-keigo/slide/10.jpg"
  - "@scenes/slide/call-phone-keigo/slide/11.jpg"
  - "@scenes/slide/call-phone-keigo/slide/12.jpg"
  - "@scenes/slide/call-phone-keigo/slide/13.jpg"
  - "@scenes/slide/call-phone-keigo/slide/14.jpg"
  - "@scenes/slide/call-phone-keigo/slide/15.jpg"
  - "@scenes/slide/call-phone-keigo/slide/16.jpg"
  - "@scenes/slide/call-phone-keigo/slide/17.jpg"
  - "@scenes/slide/call-phone-keigo/slide/18.jpg"
  - "@scenes/slide/call-phone-keigo/slide/19.jpg"
  - "@scenes/slide/call-phone-keigo/slide/20.jpg"
  - "@scenes/slide/call-phone-keigo/slide/21.jpg"
  - "@scenes/slide/call-phone-keigo/slide/22.jpg"
  - "@scenes/slide/call-phone-keigo/slide/23.jpg"
  - "@scenes/slide/call-phone-keigo/slide/24.jpg"
  - "@scenes/slide/call-phone-keigo/slide/25.jpg"
  - "@scenes/slide/call-phone-keigo/slide/26.jpg"
  - "@scenes/slide/call-phone-keigo/slide/27.jpg"
  - "@scenes/slide/call-phone-keigo/slide/28.jpg"
  - "@scenes/slide/call-phone-keigo/slide/29.jpg"
  - "@scenes/slide/call-phone-keigo/slide/30.jpg"
  - "@scenes/slide/call-phone-keigo/slide/31.jpg"
  - "@scenes/slide/call-phone-keigo/slide/32.jpg"
  - "@scenes/slide/call-phone-keigo/slide/33.jpg"
  - "@scenes/slide/call-phone-keigo/slide/34.jpg"
  - "@scenes/slide/call-phone-keigo/slide/35.jpg"
  - "@scenes/slide/call-phone-keigo/slide/36.jpg"
  - "@scenes/slide/call-phone-keigo/slide/37.jpg"
  - "@scenes/slide/call-phone-keigo/slide/38.jpg"
  - "@scenes/slide/call-phone-keigo/slide/39.jpg"
  - "@scenes/slide/call-phone-keigo/slide/40.jpg"
  - "@scenes/slide/call-phone-keigo/slide/41.jpg"
  - "@scenes/slide/call-phone-keigo/slide/42.jpg"
  - "@scenes/slide/call-phone-keigo/slide/43.jpg"
  - "@scenes/slide/call-phone-keigo/slide/44.jpg"
  - "@scenes/slide/call-phone-keigo/slide/45.jpg"
  - "@scenes/slide/call-phone-keigo/slide/46.jpg"
  - "@scenes/slide/call-phone-keigo/slide/47.jpg"
  - "@scenes/slide/call-phone-keigo/slide/48.jpg"
  - "@scenes/slide/call-phone-keigo/slide/49.jpg"
  - "@scenes/slide/call-phone-keigo/slide/50.jpg"
  - "@scenes/slide/call-phone-keigo/slide/51.jpg"
  - "@scenes/slide/call-phone-keigo/slide/52.jpg"
  - "@scenes/slide/call-phone-keigo/slide/53.jpg"
  - "@scenes/slide/call-phone-keigo/slide/54.jpg"
  - "@scenes/slide/call-phone-keigo/slide/55.jpg"
  - "@scenes/slide/call-phone-keigo/slide/56.jpg"
