title: 敬語と言葉遣い（クッション言葉）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-phone-keigo/slide/1.png"
  - "@scenes/slide/call-phone-keigo/slide/2.png"
  - "@scenes/slide/call-phone-keigo/slide/3.png"
  - "@scenes/slide/call-phone-keigo/slide/4.png"
  - "@scenes/slide/call-phone-keigo/slide/5.png"
  - "@scenes/slide/call-phone-keigo/slide/6.png"
  - "@scenes/slide/call-phone-keigo/slide/7.png"
  - "@scenes/slide/call-phone-keigo/slide/8.png"
  - "@scenes/slide/call-phone-keigo/slide/9.png"
  - "@scenes/slide/call-phone-keigo/slide/10.png"
  - "@scenes/slide/call-phone-keigo/slide/11.png"
  - "@scenes/slide/call-phone-keigo/slide/12.png"
  - "@scenes/slide/call-phone-keigo/slide/13.png"
  - "@scenes/slide/call-phone-keigo/slide/14.png"
  - "@scenes/slide/call-phone-keigo/slide/15.png"
  - "@scenes/slide/call-phone-keigo/slide/16.png"
  - "@scenes/slide/call-phone-keigo/slide/17.png"
  - "@scenes/slide/call-phone-keigo/slide/18.png"
  - "@scenes/slide/call-phone-keigo/slide/19.png"
  - "@scenes/slide/call-phone-keigo/slide/20.png"
  - "@scenes/slide/call-phone-keigo/slide/21.png"
  - "@scenes/slide/call-phone-keigo/slide/22.png"
  - "@scenes/slide/call-phone-keigo/slide/23.png"
  - "@scenes/slide/call-phone-keigo/slide/24.png"
  - "@scenes/slide/call-phone-keigo/slide/25.png"
  - "@scenes/slide/call-phone-keigo/slide/26.png"
  - "@scenes/slide/call-phone-keigo/slide/27.png"
  - "@scenes/slide/call-phone-keigo/slide/28.png"
  - "@scenes/slide/call-phone-keigo/slide/29.png"
  - "@scenes/slide/call-phone-keigo/slide/30.png"
  - "@scenes/slide/call-phone-keigo/slide/31.png"
  - "@scenes/slide/call-phone-keigo/slide/32.png"
  - "@scenes/slide/call-phone-keigo/slide/33.png"
  - "@scenes/slide/call-phone-keigo/slide/34.png"
  - "@scenes/slide/call-phone-keigo/slide/35.png"
  - "@scenes/slide/call-phone-keigo/slide/36.png"
  - "@scenes/slide/call-phone-keigo/slide/37.png"
  - "@scenes/slide/call-phone-keigo/slide/38.png"
  - "@scenes/slide/call-phone-keigo/slide/39.png"
  - "@scenes/slide/call-phone-keigo/slide/40.png"
  - "@scenes/slide/call-phone-keigo/slide/41.png"
  - "@scenes/slide/call-phone-keigo/slide/42.png"
  - "@scenes/slide/call-phone-keigo/slide/43.png"
  - "@scenes/slide/call-phone-keigo/slide/44.png"
  - "@scenes/slide/call-phone-keigo/slide/45.png"
  - "@scenes/slide/call-phone-keigo/slide/46.png"
  - "@scenes/slide/call-phone-keigo/slide/47.png"
  - "@scenes/slide/call-phone-keigo/slide/48.png"
  - "@scenes/slide/call-phone-keigo/slide/49.png"
  - "@scenes/slide/call-phone-keigo/slide/50.png"
  - "@scenes/slide/call-phone-keigo/slide/51.png"
  - "@scenes/slide/call-phone-keigo/slide/52.png"
  - "@scenes/slide/call-phone-keigo/slide/53.png"
  - "@scenes/slide/call-phone-keigo/slide/54.png"
  - "@scenes/slide/call-phone-keigo/slide/55.png"
  - "@scenes/slide/call-phone-keigo/slide/56.png"
