title: やり切る力と挑戦を続ける強さ
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-perseverance/slide/1.png"
  - "@scenes/slide/workskill03-perseverance/slide/2.png"
  - "@scenes/slide/workskill03-perseverance/slide/3.png"
  - "@scenes/slide/workskill03-perseverance/slide/4.png"
  - "@scenes/slide/workskill03-perseverance/slide/5.png"
  - "@scenes/slide/workskill03-perseverance/slide/6.png"
  - "@scenes/slide/workskill03-perseverance/slide/7.png"
  - "@scenes/slide/workskill03-perseverance/slide/8.png"
  - "@scenes/slide/workskill03-perseverance/slide/9.png"
  - "@scenes/slide/workskill03-perseverance/slide/10.png"
  - "@scenes/slide/workskill03-perseverance/slide/11.png"
  - "@scenes/slide/workskill03-perseverance/slide/12.png"
  - "@scenes/slide/workskill03-perseverance/slide/13.png"
  - "@scenes/slide/workskill03-perseverance/slide/14.png"
  - "@scenes/slide/workskill03-perseverance/slide/15.png"
  - "@scenes/slide/workskill03-perseverance/slide/16.png"
  - "@scenes/slide/workskill03-perseverance/slide/17.png"
  - "@scenes/slide/workskill03-perseverance/slide/18.png"
  - "@scenes/slide/workskill03-perseverance/slide/19.png"
  - "@scenes/slide/workskill03-perseverance/slide/20.png"
  - "@scenes/slide/workskill03-perseverance/slide/21.png"
  - "@scenes/slide/workskill03-perseverance/slide/22.png"
  - "@scenes/slide/workskill03-perseverance/slide/23.png"
  - "@scenes/slide/workskill03-perseverance/slide/24.png"
  - "@scenes/slide/workskill03-perseverance/slide/25.png"
  - "@scenes/slide/workskill03-perseverance/slide/26.png"
  - "@scenes/slide/workskill03-perseverance/slide/27.png"
  - "@scenes/slide/workskill03-perseverance/slide/28.png"
  - "@scenes/slide/workskill03-perseverance/slide/29.png"
  - "@scenes/slide/workskill03-perseverance/slide/30.png"
  - "@scenes/slide/workskill03-perseverance/slide/31.png"
  - "@scenes/slide/workskill03-perseverance/slide/32.png"
  - "@scenes/slide/workskill03-perseverance/slide/33.png"
  - "@scenes/slide/workskill03-perseverance/slide/34.png"
  - "@scenes/slide/workskill03-perseverance/slide/35.png"
  - "@scenes/slide/workskill03-perseverance/slide/36.png"
  - "@scenes/slide/workskill03-perseverance/slide/37.png"
  - "@scenes/slide/workskill03-perseverance/slide/38.png"
  - "@scenes/slide/workskill03-perseverance/slide/39.png"
  - "@scenes/slide/workskill03-perseverance/slide/40.png"
  - "@scenes/slide/workskill03-perseverance/slide/41.png"
  - "@scenes/slide/workskill03-perseverance/slide/42.png"
  - "@scenes/slide/workskill03-perseverance/slide/43.png"
  - "@scenes/slide/workskill03-perseverance/slide/44.png"
