title: やり切る力と挑戦を続ける強さ
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-perseverance/slide/1.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/2.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/3.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/4.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/5.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/6.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/7.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/8.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/9.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/10.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/11.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/12.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/13.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/14.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/15.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/16.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/17.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/18.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/19.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/20.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/21.jpg"
  - "@scenes/slide/workskill03-perseverance/slide/22.jpg"
