title: 轻松理解！物流入门Ⅱ UNIT1
btn_next_scene_name: 下一个
slide_speed: 10
img:
  - "@scenes/slide/zh-logistics02-unit01/slide/1.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/2.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/3.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/4.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/5.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/6.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/7.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/8.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/9.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/10.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/11.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/12.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/13.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/14.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/15.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/16.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/17.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/18.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/19.png"
  - "@scenes/slide/zh-logistics02-unit01/slide/20.png"
