title: 積極性と周囲に良い影響を与える力
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-influence/slide/1.jpg"
  - "@scenes/slide/workskill03-influence/slide/2.jpg"
  - "@scenes/slide/workskill03-influence/slide/3.jpg"
  - "@scenes/slide/workskill03-influence/slide/4.jpg"
  - "@scenes/slide/workskill03-influence/slide/5.jpg"
  - "@scenes/slide/workskill03-influence/slide/6.jpg"
  - "@scenes/slide/workskill03-influence/slide/7.jpg"
  - "@scenes/slide/workskill03-influence/slide/8.jpg"
  - "@scenes/slide/workskill03-influence/slide/9.jpg"
  - "@scenes/slide/workskill03-influence/slide/10.jpg"
  - "@scenes/slide/workskill03-influence/slide/11.jpg"
  - "@scenes/slide/workskill03-influence/slide/12.jpg"
  - "@scenes/slide/workskill03-influence/slide/13.jpg"
  - "@scenes/slide/workskill03-influence/slide/14.jpg"
  - "@scenes/slide/workskill03-influence/slide/15.jpg"
  - "@scenes/slide/workskill03-influence/slide/16.jpg"
  - "@scenes/slide/workskill03-influence/slide/17.jpg"
  - "@scenes/slide/workskill03-influence/slide/18.jpg"
  - "@scenes/slide/workskill03-influence/slide/19.jpg"
  - "@scenes/slide/workskill03-influence/slide/20.jpg"
  - "@scenes/slide/workskill03-influence/slide/21.jpg"
  - "@scenes/slide/workskill03-influence/slide/22.jpg"
