title: 積極性と周囲に良い影響を与える力
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/workskill03-influence/slide/1.png"
  - "@scenes/slide/workskill03-influence/slide/2.png"
  - "@scenes/slide/workskill03-influence/slide/3.png"
  - "@scenes/slide/workskill03-influence/slide/4.png"
  - "@scenes/slide/workskill03-influence/slide/5.png"
  - "@scenes/slide/workskill03-influence/slide/6.png"
  - "@scenes/slide/workskill03-influence/slide/7.png"
  - "@scenes/slide/workskill03-influence/slide/8.png"
  - "@scenes/slide/workskill03-influence/slide/9.png"
  - "@scenes/slide/workskill03-influence/slide/10.png"
  - "@scenes/slide/workskill03-influence/slide/11.png"
  - "@scenes/slide/workskill03-influence/slide/12.png"
  - "@scenes/slide/workskill03-influence/slide/13.png"
  - "@scenes/slide/workskill03-influence/slide/14.png"
  - "@scenes/slide/workskill03-influence/slide/15.png"
  - "@scenes/slide/workskill03-influence/slide/16.png"
  - "@scenes/slide/workskill03-influence/slide/17.png"
  - "@scenes/slide/workskill03-influence/slide/18.png"
  - "@scenes/slide/workskill03-influence/slide/19.png"
  - "@scenes/slide/workskill03-influence/slide/20.png"
  - "@scenes/slide/workskill03-influence/slide/21.png"
  - "@scenes/slide/workskill03-influence/slide/22.png"
  - "@scenes/slide/workskill03-influence/slide/23.png"
  - "@scenes/slide/workskill03-influence/slide/24.png"
  - "@scenes/slide/workskill03-influence/slide/25.png"
  - "@scenes/slide/workskill03-influence/slide/26.png"
  - "@scenes/slide/workskill03-influence/slide/27.png"
  - "@scenes/slide/workskill03-influence/slide/28.png"
  - "@scenes/slide/workskill03-influence/slide/29.png"
  - "@scenes/slide/workskill03-influence/slide/30.png"
  - "@scenes/slide/workskill03-influence/slide/31.png"
  - "@scenes/slide/workskill03-influence/slide/32.png"
  - "@scenes/slide/workskill03-influence/slide/33.png"
  - "@scenes/slide/workskill03-influence/slide/34.png"
  - "@scenes/slide/workskill03-influence/slide/35.png"
  - "@scenes/slide/workskill03-influence/slide/36.png"
  - "@scenes/slide/workskill03-influence/slide/37.png"
  - "@scenes/slide/workskill03-influence/slide/38.png"
  - "@scenes/slide/workskill03-influence/slide/39.png"
  - "@scenes/slide/workskill03-influence/slide/40.png"
  - "@scenes/slide/workskill03-influence/slide/41.png"
  - "@scenes/slide/workskill03-influence/slide/42.png"
  - "@scenes/slide/workskill03-influence/slide/43.png"
  - "@scenes/slide/workskill03-influence/slide/44.png"
