title: Password and Device Management
btn_next_scene_name: Next
slide_speed: 10
img:
  - "@scenes/slide/security-password/slide/1.jpg"
  - "@scenes/slide/security-password/slide/2.jpg"
  - "@scenes/slide/security-password/slide/3.jpg"
  - "@scenes/slide/security-password/slide/4.jpg"
  - "@scenes/slide/security-password/slide/5.jpg"
  - "@scenes/slide/security-password/slide/6.jpg"
  - "@scenes/slide/security-password/slide/7.jpg"
  - "@scenes/slide/security-password/slide/8.jpg"
  - "@scenes/slide/security-password/slide/9.jpg"
  - "@scenes/slide/security-password/slide/10.jpg"
  - "@scenes/slide/security-password/slide/11.jpg"
  - "@scenes/slide/security-password/slide/12.jpg"
  - "@scenes/slide/security-password/slide/13.jpg"
  - "@scenes/slide/security-password/slide/14.jpg"
  - "@scenes/slide/security-password/slide/15.jpg"
  - "@scenes/slide/security-password/slide/16.jpg"
  - "@scenes/slide/security-password/slide/17.jpg"
  - "@scenes/slide/security-password/slide/18.jpg"
  - "@scenes/slide/security-password/slide/19.jpg"
  - "@scenes/slide/security-password/slide/20.jpg"
  - "@scenes/slide/security-password/slide/21.jpg"
  - "@scenes/slide/security-password/slide/22.jpg"
