title: 正確・簡潔・分かりやすい文章術（PREP法）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/biz-doc-prep/slide/1.jpg"
  - "@scenes/slide/biz-doc-prep/slide/2.jpg"
  - "@scenes/slide/biz-doc-prep/slide/3.jpg"
  - "@scenes/slide/biz-doc-prep/slide/4.jpg"
  - "@scenes/slide/biz-doc-prep/slide/5.jpg"
  - "@scenes/slide/biz-doc-prep/slide/6.jpg"
  - "@scenes/slide/biz-doc-prep/slide/7.jpg"
  - "@scenes/slide/biz-doc-prep/slide/8.jpg"
  - "@scenes/slide/biz-doc-prep/slide/9.jpg"
  - "@scenes/slide/biz-doc-prep/slide/10.jpg"
  - "@scenes/slide/biz-doc-prep/slide/11.jpg"
  - "@scenes/slide/biz-doc-prep/slide/12.jpg"
  - "@scenes/slide/biz-doc-prep/slide/13.jpg"
  - "@scenes/slide/biz-doc-prep/slide/14.jpg"
  - "@scenes/slide/biz-doc-prep/slide/15.jpg"
  - "@scenes/slide/biz-doc-prep/slide/16.jpg"
  - "@scenes/slide/biz-doc-prep/slide/17.jpg"
  - "@scenes/slide/biz-doc-prep/slide/18.jpg"
  - "@scenes/slide/biz-doc-prep/slide/19.jpg"
  - "@scenes/slide/biz-doc-prep/slide/20.jpg"
  - "@scenes/slide/biz-doc-prep/slide/21.jpg"
  - "@scenes/slide/biz-doc-prep/slide/22.jpg"
  - "@scenes/slide/biz-doc-prep/slide/23.jpg"
  - "@scenes/slide/biz-doc-prep/slide/24.jpg"
  - "@scenes/slide/biz-doc-prep/slide/25.jpg"
  - "@scenes/slide/biz-doc-prep/slide/26.jpg"
  - "@scenes/slide/biz-doc-prep/slide/27.jpg"
  - "@scenes/slide/biz-doc-prep/slide/28.jpg"
