title: 正確・簡潔・分かりやすい文章術（PREP法）
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/biz-doc-prep/slide/1.png"
  - "@scenes/slide/biz-doc-prep/slide/2.png"
  - "@scenes/slide/biz-doc-prep/slide/3.png"
  - "@scenes/slide/biz-doc-prep/slide/4.png"
  - "@scenes/slide/biz-doc-prep/slide/5.png"
  - "@scenes/slide/biz-doc-prep/slide/6.png"
  - "@scenes/slide/biz-doc-prep/slide/7.png"
  - "@scenes/slide/biz-doc-prep/slide/8.png"
  - "@scenes/slide/biz-doc-prep/slide/9.png"
  - "@scenes/slide/biz-doc-prep/slide/10.png"
  - "@scenes/slide/biz-doc-prep/slide/11.png"
  - "@scenes/slide/biz-doc-prep/slide/12.png"
  - "@scenes/slide/biz-doc-prep/slide/13.png"
  - "@scenes/slide/biz-doc-prep/slide/14.png"
  - "@scenes/slide/biz-doc-prep/slide/15.png"
  - "@scenes/slide/biz-doc-prep/slide/16.png"
  - "@scenes/slide/biz-doc-prep/slide/17.png"
  - "@scenes/slide/biz-doc-prep/slide/18.png"
  - "@scenes/slide/biz-doc-prep/slide/19.png"
  - "@scenes/slide/biz-doc-prep/slide/20.png"
  - "@scenes/slide/biz-doc-prep/slide/21.png"
  - "@scenes/slide/biz-doc-prep/slide/22.png"
  - "@scenes/slide/biz-doc-prep/slide/23.png"
  - "@scenes/slide/biz-doc-prep/slide/24.png"
  - "@scenes/slide/biz-doc-prep/slide/25.png"
  - "@scenes/slide/biz-doc-prep/slide/26.png"
  - "@scenes/slide/biz-doc-prep/slide/27.png"
  - "@scenes/slide/biz-doc-prep/slide/28.png"
  - "@scenes/slide/biz-doc-prep/slide/29.png"
  - "@scenes/slide/biz-doc-prep/slide/30.png"
  - "@scenes/slide/biz-doc-prep/slide/31.png"
  - "@scenes/slide/biz-doc-prep/slide/32.png"
  - "@scenes/slide/biz-doc-prep/slide/33.png"
  - "@scenes/slide/biz-doc-prep/slide/34.png"
  - "@scenes/slide/biz-doc-prep/slide/35.png"
  - "@scenes/slide/biz-doc-prep/slide/36.png"
  - "@scenes/slide/biz-doc-prep/slide/37.png"
  - "@scenes/slide/biz-doc-prep/slide/38.png"
  - "@scenes/slide/biz-doc-prep/slide/39.png"
  - "@scenes/slide/biz-doc-prep/slide/40.png"
  - "@scenes/slide/biz-doc-prep/slide/41.png"
  - "@scenes/slide/biz-doc-prep/slide/42.png"
  - "@scenes/slide/biz-doc-prep/slide/43.png"
  - "@scenes/slide/biz-doc-prep/slide/44.png"
  - "@scenes/slide/biz-doc-prep/slide/45.png"
  - "@scenes/slide/biz-doc-prep/slide/46.png"
  - "@scenes/slide/biz-doc-prep/slide/47.png"
  - "@scenes/slide/biz-doc-prep/slide/48.png"
  - "@scenes/slide/biz-doc-prep/slide/49.png"
  - "@scenes/slide/biz-doc-prep/slide/50.png"
  - "@scenes/slide/biz-doc-prep/slide/51.png"
  - "@scenes/slide/biz-doc-prep/slide/52.png"
  - "@scenes/slide/biz-doc-prep/slide/53.png"
  - "@scenes/slide/biz-doc-prep/slide/54.png"
  - "@scenes/slide/biz-doc-prep/slide/55.png"
