title: アンガーマネジメントの基礎
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-power-anger/slide/1.png"
  - "@scenes/slide/harass-power-anger/slide/2.png"
  - "@scenes/slide/harass-power-anger/slide/3.png"
  - "@scenes/slide/harass-power-anger/slide/4.png"
  - "@scenes/slide/harass-power-anger/slide/5.png"
  - "@scenes/slide/harass-power-anger/slide/6.png"
  - "@scenes/slide/harass-power-anger/slide/7.png"
  - "@scenes/slide/harass-power-anger/slide/8.png"
  - "@scenes/slide/harass-power-anger/slide/9.png"
  - "@scenes/slide/harass-power-anger/slide/10.png"
  - "@scenes/slide/harass-power-anger/slide/11.png"
  - "@scenes/slide/harass-power-anger/slide/12.png"
  - "@scenes/slide/harass-power-anger/slide/13.png"
  - "@scenes/slide/harass-power-anger/slide/14.png"
  - "@scenes/slide/harass-power-anger/slide/15.png"
  - "@scenes/slide/harass-power-anger/slide/16.png"
  - "@scenes/slide/harass-power-anger/slide/17.png"
  - "@scenes/slide/harass-power-anger/slide/18.png"
  - "@scenes/slide/harass-power-anger/slide/19.png"
  - "@scenes/slide/harass-power-anger/slide/20.png"
  - "@scenes/slide/harass-power-anger/slide/21.png"
  - "@scenes/slide/harass-power-anger/slide/22.png"
  - "@scenes/slide/harass-power-anger/slide/23.png"
  - "@scenes/slide/harass-power-anger/slide/24.png"
  - "@scenes/slide/harass-power-anger/slide/25.png"
  - "@scenes/slide/harass-power-anger/slide/26.png"
  - "@scenes/slide/harass-power-anger/slide/27.png"
  - "@scenes/slide/harass-power-anger/slide/28.png"
  - "@scenes/slide/harass-power-anger/slide/29.png"
  - "@scenes/slide/harass-power-anger/slide/30.png"
  - "@scenes/slide/harass-power-anger/slide/31.png"
  - "@scenes/slide/harass-power-anger/slide/32.png"
  - "@scenes/slide/harass-power-anger/slide/33.png"
  - "@scenes/slide/harass-power-anger/slide/34.png"
  - "@scenes/slide/harass-power-anger/slide/35.png"
  - "@scenes/slide/harass-power-anger/slide/36.png"
  - "@scenes/slide/harass-power-anger/slide/37.png"
  - "@scenes/slide/harass-power-anger/slide/38.png"
  - "@scenes/slide/harass-power-anger/slide/39.png"
  - "@scenes/slide/harass-power-anger/slide/40.png"
  - "@scenes/slide/harass-power-anger/slide/41.png"
  - "@scenes/slide/harass-power-anger/slide/42.png"
  - "@scenes/slide/harass-power-anger/slide/43.png"
  - "@scenes/slide/harass-power-anger/slide/44.png"
  - "@scenes/slide/harass-power-anger/slide/45.png"
  - "@scenes/slide/harass-power-anger/slide/46.png"
  - "@scenes/slide/harass-power-anger/slide/47.png"
  - "@scenes/slide/harass-power-anger/slide/48.png"
  - "@scenes/slide/harass-power-anger/slide/49.png"
