title: アンガーマネジメントの基礎
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/harass-power-anger/slide/1.jpg"
  - "@scenes/slide/harass-power-anger/slide/2.jpg"
  - "@scenes/slide/harass-power-anger/slide/3.jpg"
  - "@scenes/slide/harass-power-anger/slide/4.jpg"
  - "@scenes/slide/harass-power-anger/slide/5.jpg"
  - "@scenes/slide/harass-power-anger/slide/6.jpg"
  - "@scenes/slide/harass-power-anger/slide/7.jpg"
  - "@scenes/slide/harass-power-anger/slide/8.jpg"
  - "@scenes/slide/harass-power-anger/slide/9.jpg"
  - "@scenes/slide/harass-power-anger/slide/10.jpg"
  - "@scenes/slide/harass-power-anger/slide/11.jpg"
  - "@scenes/slide/harass-power-anger/slide/12.jpg"
  - "@scenes/slide/harass-power-anger/slide/13.jpg"
  - "@scenes/slide/harass-power-anger/slide/14.jpg"
  - "@scenes/slide/harass-power-anger/slide/15.jpg"
  - "@scenes/slide/harass-power-anger/slide/16.jpg"
  - "@scenes/slide/harass-power-anger/slide/17.jpg"
  - "@scenes/slide/harass-power-anger/slide/18.jpg"
  - "@scenes/slide/harass-power-anger/slide/19.jpg"
  - "@scenes/slide/harass-power-anger/slide/20.jpg"
  - "@scenes/slide/harass-power-anger/slide/21.jpg"
  - "@scenes/slide/harass-power-anger/slide/22.jpg"
  - "@scenes/slide/harass-power-anger/slide/23.jpg"
  - "@scenes/slide/harass-power-anger/slide/24.jpg"
  - "@scenes/slide/harass-power-anger/slide/25.jpg"
