title: 解決提案とクロージング
btn_next_scene_name: 次へ
slide_speed: 10
img:
  - "@scenes/slide/call-claim-closing/slide/1.jpg"
  - "@scenes/slide/call-claim-closing/slide/2.jpg"
  - "@scenes/slide/call-claim-closing/slide/3.jpg"
  - "@scenes/slide/call-claim-closing/slide/4.jpg"
  - "@scenes/slide/call-claim-closing/slide/5.jpg"
  - "@scenes/slide/call-claim-closing/slide/6.jpg"
  - "@scenes/slide/call-claim-closing/slide/7.jpg"
  - "@scenes/slide/call-claim-closing/slide/8.jpg"
  - "@scenes/slide/call-claim-closing/slide/9.jpg"
  - "@scenes/slide/call-claim-closing/slide/10.jpg"
  - "@scenes/slide/call-claim-closing/slide/11.jpg"
  - "@scenes/slide/call-claim-closing/slide/12.jpg"
  - "@scenes/slide/call-claim-closing/slide/13.jpg"
  - "@scenes/slide/call-claim-closing/slide/14.jpg"
  - "@scenes/slide/call-claim-closing/slide/15.jpg"
  - "@scenes/slide/call-claim-closing/slide/16.jpg"
  - "@scenes/slide/call-claim-closing/slide/17.jpg"
  - "@scenes/slide/call-claim-closing/slide/18.jpg"
  - "@scenes/slide/call-claim-closing/slide/19.jpg"
  - "@scenes/slide/call-claim-closing/slide/20.jpg"
  - "@scenes/slide/call-claim-closing/slide/21.jpg"
  - "@scenes/slide/call-claim-closing/slide/22.jpg"
  - "@scenes/slide/call-claim-closing/slide/23.jpg"
  - "@scenes/slide/call-claim-closing/slide/24.jpg"
  - "@scenes/slide/call-claim-closing/slide/25.jpg"
  - "@scenes/slide/call-claim-closing/slide/26.jpg"
  - "@scenes/slide/call-claim-closing/slide/27.jpg"
  - "@scenes/slide/call-claim-closing/slide/28.jpg"
  - "@scenes/slide/call-claim-closing/slide/29.jpg"
  - "@scenes/slide/call-claim-closing/slide/30.jpg"
  - "@scenes/slide/call-claim-closing/slide/31.jpg"
  - "@scenes/slide/call-claim-closing/slide/32.jpg"
  - "@scenes/slide/call-claim-closing/slide/33.jpg"
  - "@scenes/slide/call-claim-closing/slide/34.jpg"
  - "@scenes/slide/call-claim-closing/slide/35.jpg"
  - "@scenes/slide/call-claim-closing/slide/36.jpg"
  - "@scenes/slide/call-claim-closing/slide/37.jpg"
  - "@scenes/slide/call-claim-closing/slide/38.jpg"
  - "@scenes/slide/call-claim-closing/slide/39.jpg"
  - "@scenes/slide/call-claim-closing/slide/40.jpg"
  - "@scenes/slide/call-claim-closing/slide/41.jpg"
  - "@scenes/slide/call-claim-closing/slide/42.jpg"
  - "@scenes/slide/call-claim-closing/slide/43.jpg"
  - "@scenes/slide/call-claim-closing/slide/44.jpg"
  - "@scenes/slide/call-claim-closing/slide/45.jpg"
  - "@scenes/slide/call-claim-closing/slide/46.jpg"
  - "@scenes/slide/call-claim-closing/slide/47.jpg"
  - "@scenes/slide/call-claim-closing/slide/48.jpg"
  - "@scenes/slide/call-claim-closing/slide/49.jpg"
  - "@scenes/slide/call-claim-closing/slide/50.jpg"
  - "@scenes/slide/call-claim-closing/slide/51.jpg"
  - "@scenes/slide/call-claim-closing/slide/52.jpg"
  - "@scenes/slide/call-claim-closing/slide/53.jpg"
  - "@scenes/slide/call-claim-closing/slide/54.jpg"
  - "@scenes/slide/call-claim-closing/slide/55.jpg"
  - "@scenes/slide/call-claim-closing/slide/56.jpg"
  - "@scenes/slide/call-claim-closing/slide/57.jpg"
  - "@scenes/slide/call-claim-closing/slide/58.jpg"
  - "@scenes/slide/call-claim-closing/slide/59.jpg"
